### ISSUE TITLE
[HyBox/production] RSolr::Error::Http: RSolr::Error::Http - 404 Not FoundError

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#1002]
```
Not Found URI: http://solr.demo.vpc.hydrainabox.org/solr/update?wt=ruby&softCommit=true Request Headers: {"Content-Type"=>"text/xml"} Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"system_create_dtsi\">2017-04-26T22:50:51Z</field><field name=\"system_modified_dtsi\">2017-04-26T22:50:51Z</field><field name=\"has_model_ssim\">Hydra::AccessControl</field><field name=\"id\">32c8d44b-ab98-45...
```
## Backtrace

    line 3 of [PROJECT_ROOT]/app/jobs/create_default_admin_set_job.rb: perform
    line 26 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in perform_now
    line 42 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in switch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/33414140)

**Comment by mjgiarlo** [comment]
Fixed with #1005.
