### ISSUE TITLE
Cleanup corrupted Account data

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyku#1012]
Various accounts have been partially created and are stuck in a zombie state.  Many have duplicate `cname` values, which means they are confusingly associated with multiple tenants.

```
hybox=> select count(cname) from accounts;
 count 
-------
    86
(1 row)

hybox=> select count(DISTINCT cname) from accounts;
 count 
-------
    76
(1 row)

hybox=> select * from (select cname, count(cname) from accounts GROUP BY cname) as foo where count > 1;
              cname               | count 
----------------------------------+-------
 gary.demo.hydrainabox.org        |     2
 fresh.demo.hydrainabox.org       |     3
 foo.demo.hydrainabox.org         |     2
 foos-of-bar.demo.hydrainabox.org |     4
 foobar.demo.hydrainabox.org      |     4
(5 rows)
```

This is despite our model declaring:
```ruby
validates :cname, presence: true, uniqueness: true, exclusion: { in: [default_cname('')] }
```

So despite our tested validation logic working in isolation, it has failed to prevent duplicate `cname` values in the database.  Interestingly, I think this failure is not the general-case failure of Rails uniqueness validations in a multi-webserver single-DB environment.  

So the task is twofold:
- [ ] Decide how to clean up the existing data and do it.
- [ ] Decide how to prevent further corruption and do it.

I would nuke the duplicate accounts and pursue a DB-level uniqueness constraint on `cname`.  

@mjgiarlo

**Comment by atz** [comment]
Mechanism of failure:
`AccountElevator` does:
```
  def parse_tenant_name(request)
    account = Account.from_request(request)
    account.tenant if account
  end
```

`Account` has:
```ruby
  def self.from_request(request)
    find_by(cname: canonical_cname(request.host))
  end
```

ActiveRecord's [`find_by`](http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by) method just returns the first match.  If there are many (and we just determined there are), the results are undetermined (possibly cache-dependent).

**Comment by jcoyne** [comment]
That validation doesn't appear to work because it's looking for a domain with a period on the end of it.  This is on production:
```ruby
irb(main):015:0> a = Account.new(name: 'fresh')
=> #<Account id: nil, tenant: nil, cname: nil, created_at: nil, updated_at: nil, solr_endpoint_id: nil, fcrepo_endpoint_id: nil, name: "fresh", redis_endpoint_id: nil, title: nil>
irb(main):016:0> a.valid?
  Account Exists (0.8ms)  SELECT  1 AS one FROM "public"."accounts" WHERE "public"."accounts"."tenant" = $1 LIMIT $2  [["tenant", "d9f826aa-dabc-4294-a0e1-ded4a08da19d"], ["LIMIT", 1]]
  Account Exists (0.5ms)  SELECT  1 AS one FROM "public"."accounts" WHERE "public"."accounts"."cname" = $1 LIMIT $2  [["cname", "fresh.demo.hydrainabox.org."], ["LIMIT", 1]]
=> true
irb(main):017:0> a.save
   (0.6ms)  BEGIN
  Account Exists (0.7ms)  SELECT  1 AS one FROM "public"."accounts" WHERE "public"."accounts"."tenant" = $1 LIMIT $2  [["tenant", "d9f826aa-dabc-4294-a0e1-ded4a08da19d"], ["LIMIT", 1]]
  Account Exists (0.5ms)  SELECT  1 AS one FROM "public"."accounts" WHERE "public"."accounts"."cname" = $1 LIMIT $2  [["cname", "fresh.demo.hydrainabox.org."], ["LIMIT", 1]]
  SQL (0.5ms)  INSERT INTO "public"."accounts" ("tenant", "cname", "created_at", "updated_at", "name") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["tenant", "d9f826aa-dabc-4294-a0e1-ded4a08da19d"], ["cname", "fresh.demo.hydrainabox.org"], ["created_at", 2017-04-28 03:36:26 UTC], ["updated_at", 2017-04-28 03:36:26 UTC], ["name", "fresh"]]
   (3.4ms)  COMMIT
=> true
```

**Comment by jcoyne** [comment]
The period is probably produced by `Account.default_cname`
```ruby
Account.default_cname('fresh')
=> "fresh.demo.hydrainabox.org."
```

**Comment by jcoyne** [comment]
Which is in turn a result of default host having a trailing period:
```ruby
Settings.multitenancy.default_host
=> "%{tenant}.demo.hydrainabox.org."
```

@cbeer is there a reason for that? Should the output of `Account.default_cname` be canonicalized?

**Comment by jcoyne** [comment]
It appears that `MULTITENANCY__DEFAULT_HOST` comes from `HostedZoneName`:

https://github.com/hybox/aws/blob/master/templates/webapp.yaml#L290

all the zone names end in a period: https://console.aws.amazon.com/route53/home?region=us-east-1#hosted-zones

**Comment by mjgiarlo** [comment]
@atz :speech_balloon: 
> I would nuke the duplicate accounts and pursue a DB-level uniqueness constraint on cname.
> 
> @mjgiarlo

:shipit:, taking @jcoyne's findings above into account.

**Comment by atz** [comment]
@mjgiarlo Happy to begin cleanup.  Seems the correct way to go is `CleanupAccountJob(account)`.  Note: that job doesn't do anything for Redis cleanup. 

Do we need to do any notifications?

**Comment by mjgiarlo** [comment]
@atz You mean in-app notifications? Do superadmins get/see notifications in the UI? I don't have strong feelings about this.

**Comment by mjgiarlo** [comment]
@hannahfrost @ggeisler thoughts on the above?

**Comment by atz** [comment]
No, I mean, do we need to email anybody about deleting their stuff?

**Comment by hannahfrost** [comment]
All current tenants being deleted? That's fine

**Comment by mjgiarlo** [comment]
Agree with @hannahfrost: we're clear to do targeted cleanup of dupe accounts anytime. I also agree that we are clear to do a complete teardown/rebuild whenever we want (though preferably before 5/15 when people start kicking the tires on the beta).

**Comment by mjgiarlo** [comment]
Once https://github.com/projecthydra-labs/hyku/pull/1027 is merged, this can proceed.

Alternatively, let the stack teardown/rebuild "take care" of this.

**Comment by mjgiarlo** [comment]
@atz @hannahfrost Resolved: @eefahy is going to teardown the whole stack today, so we don't need cleanup of this account data.

Close?
