### ISSUE TITLE
error on work submit

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#1015]
Submission of a work failed, resulting in the message: "The page you were looking for doesn't exist.You may have mistyped the address or the page may have moved."

details: by a proxy depositor, embargoed, to default admin set, single image file.

**Comment by hannahfrost** [comment]
I used the back button to return to the failed submission. All metadata was still in the form, but the file was not. I reuploaded the file and resubmitted. Same error. Was able to reproduce this twice total. Tried a different file, but still unable to submit.

**Comment by hannahfrost** [comment]
Changed embargo settings and tried to submit a new work; no dice. Could it be something with the default admin set? My other admin set takes works

**Comment by hannahfrost** [comment]
I tried to submit again today to this same default admin set and got the same error. Then I created a new tenant, and added a work to the default admin set without issue.  So I can reproduce the issue in the original set but not the other newer one. Not sure if this is worth investigating in the old tenant, perhaps it was an anomaly.

**Comment by mjgiarlo** [comment]
@hannahfrost can you try this again in the newly rebuilt stack?

**Comment by hannahfrost** [comment]
cannot duplicate in newly rebulit stack 🎉
