### ISSUE TITLE
facets are missing on search results

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#1018]

**Comment by darrenleeweber** [comment]
@hannahfrost - how can I replicate this bug (sorry, it's not obvious to me)

**Comment by darrenleeweber** [comment]
Removing myself from this issue - not enough information to understand and replicate the bug.

**Comment by jcoyne** [comment]
@darrenleeweber See no facets: https://hyphy.demo.hydrainabox.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=

**Comment by darrenleeweber** [comment]
OK, thanks.

Also found workflow description in google doc, e.g.

- Workflow: Search for a term
  - Search for a term or phrase, review results, select a record to view. The search bar includes a button on the right to filter results.
  - Main page with search bar in top bar:
    - https://a11y.demo.hydrainabox.org/

- The search results page adds a group of facets on the left, a sort widget, a pagination widget, and buttons for altering the view type:
  - https://a11y.demo.hydrainabox.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=foobar
  - But that HyKu instance is gone

**Comment by darrenleeweber** [comment]
Now I need to figure out how to replicate that on my laptop (I guess).

**Comment by darrenleeweber** [comment]
Poking around with firebug, noticed there is an empty `sidebar` div, i.e.
```html
<div class="col-xs-12">
<div id="sidebar" class="col-md-3 col-sm-4"> </div>
```

**Comment by dlpierce** [comment]
I think this may be fixed by the above PR. Metadata was not being index into solr, so it's not surprising no facets were being displayed.

**Comment by mjgiarlo** [comment]
I am now seeing facets. Closing. Thank you, @dlpierce!
