### ISSUE TITLE
download file is not working as expected

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#1024]
When I click "download", the file loads in a browser window. Download to my local system does not start by itself after clicking a "download" link as one would expect.

On Chrome 58 and Safari 10.1

**Comment by jcoyne** [comment]
Duplicate of https://github.com/projecthydra-labs/hyrax/issues/598 ?

**Comment by mjgiarlo** [comment]
Yes, I believe this is a dup.
