### ISSUE TITLE
./bin/setup - postgres details outdated?

### ISSUE THREAD

**Issue by darrenleeweber** [projecthydra-labs/hyku#1037]
### Descriptive summary

https://github.com/projecthydra-labs/hyku#for-development
- are the postgres details outdated?
- there is no `./db/postgres` file
- while running `./bin/setup`, there are warnings about tenancy, i.e.

```
$ bundle exec ./bin/setup

... snipped everything prior, it all worked OK ...

== Loading workflows
        [WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.

... snipped everything after, it all worked OK ...
```

**Comment by jcoyne** [comment]
I can't speak to the instructions, but the warnings you listed are expected and can be disregarded.  They are not related to the postgres configuration

**Comment by darrenleeweber** [comment]
Similar comment about missing `./db/postgres` applies to the test instructions, i.e.
- https://github.com/projecthydra-labs/hyku/wiki/Hyku-Development-Guide

**Comment by atz** [comment]
`./db/postgres` refers to a directory, specifically the postgres "datadir", i.e. where you want postgres to run.  You could create it anywhere on your system.
