### ISSUE TITLE
New repo on AWS contains another user's Work 

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#1050]
### Descriptive summary

Not sure if this is a known bug being worked on but ... on creating a new repo on demo.hydrainabox.org there is a work that already exists in the default admin set, created by another user, yesterday.

### Expected behavior
I should see a default admin set, but it should be empty.

### Actual behavior
Tried twice with different repos and each time I see the same Work in my default admin set.

### Steps to reproduce the behavior

1. Create a new repo on demo.hydrainabox.org
1. Go to Administrative Sets.
![index_admin_set____hyku](https://cloud.githubusercontent.com/assets/101482/25679186/3b25efae-3001-11e7-8e98-66c65bd90727.png)

1. Click on the Default Admin Set. I see a work titled "VAD777"
![show_admin_set____hyku](https://cloud.githubusercontent.com/assets/101482/25679188/3f4c9826-3001-11e7-8bba-5f198cbff97c.png)
1. Click on the work
1. Click on the work title in the Items section to get to the Files page:
![show_file_set____hyku](https://cloud.githubusercontent.com/assets/101482/25679223/60804632-3001-11e7-8fa5-8d45d8a45a02.png)

https://ggstanford.demo.hydrainabox.org/concern/parent/6ebd40ea-8928-4583-8054-cd20b779bb9c/file_sets/50ccf470-2dbf-4d95-a10a-eb78e6f6b8f9

**Comment by jcoyne** [comment]
cc @randalldfloyd do you know what's going on there?

**Comment by randalldfloyd** [comment]
@jcoyne @ggeisler I created that work while in my tenant at https://iu-repo.demo.hydrainabox.org . I see the work when viewing my works in my dashboard.

**Comment by atz** [comment]
First think I notice is that half the accounts including @ggeisler's do not have endpoints in the database.  This means the account creation jobs failed somehow.
```
hybox=> select cname,created_at,updated_at,solr_endpoint_id,fcrepo_endpoint_id,redis_endpoint_id from accounts;
                cname                 |         created_at         |         updated_at         | solr_endpoint_id | fcrepo_endpoint_id | redis_endpoint_id 
--------------------------------------+----------------------------+----------------------------+------------------+--------------------+-------------------
 cubs.demo.hydrainabox.org            | 2017-05-02 05:04:25.417394 | 2017-05-02 05:04:41.658587 |                1 |                  2 |                 3
 hyphy.demo.hydrainabox.org           | 2017-05-02 12:50:45.701398 | 2017-05-02 12:51:01.517844 |                4 |                  5 |                 6
 iu-repo.demo.hydrainabox.org         | 2017-05-02 15:30:24.313625 | 2017-05-02 15:30:39.997627 |                7 |                  8 |                 9
 troubleshooting.demo.hydrainabox.org | 2017-05-02 18:13:05.932055 | 2017-05-02 18:13:25.343283 |               10 |                 11 |                12
 fruit.demo.hydrainabox.org           | 2017-05-02 23:32:12.773409 | 2017-05-02 23:32:27.281077 |               13 |                 14 |                15
 acme.demo.hydrainabox.org            | 2017-05-03 04:11:04.430945 | 2017-05-03 04:11:19.327859 |               16 |                 17 |                18
 ajs.demo.hydrainabox.org             | 2017-05-03 15:12:06.538236 | 2017-05-03 15:12:06.538236 |                  |                    |                  
 pear.demo.hydrainabox.org            | 2017-05-03 17:50:22.649465 | 2017-05-03 17:50:22.649465 |                  |                    |                  
 bbtesttenant.demo.hydrainabox.org    | 2017-05-03 18:51:09.438584 | 2017-05-03 18:51:09.438584 |                  |                    |                  
 gg.demo.hydrainabox.org              | 2017-05-03 19:54:05.947005 | 2017-05-03 19:54:05.947005 |                  |                    |                  
 ggstanford.demo.hydrainabox.org      | 2017-05-03 19:56:46.080639 | 2017-05-03 19:56:46.080639 |                  |                    |                  
 bbtesttenant2.demo.hydrainabox.org   | 2017-05-03 23:38:57.755706 | 2017-05-03 23:38:57.755706 |                  |                    |                  
(12 rows)
```

**Comment by atz** [comment]
I'm not sure how those accounts would see *any* solr or fedora data.

**Comment by atz** [comment]
@bbranan: it looks like your suspicion that the zookeeper break/fix caused this is substantiated.  More recently created accounts are OK:
```
hybox=> select cname,created_at,updated_at,solr_endpoint_id,fcrepo_endpoint_id,redis_endpoint_id from accounts;
                cname                 |         created_at         |         updated_at         | solr_endpoint_id | fcrepo_endpoint_id | redis_endpoint_id 
--------------------------------------+----------------------------+----------------------------+------------------+--------------------+-------------------
 cubs.demo.hydrainabox.org            | 2017-05-02 05:04:25.417394 | 2017-05-02 05:04:41.658587 |                1 |                  2 |                 3
 hyphy.demo.hydrainabox.org           | 2017-05-02 12:50:45.701398 | 2017-05-02 12:51:01.517844 |                4 |                  5 |                 6
 iu-repo.demo.hydrainabox.org         | 2017-05-02 15:30:24.313625 | 2017-05-02 15:30:39.997627 |                7 |                  8 |                 9
 troubleshooting.demo.hydrainabox.org | 2017-05-02 18:13:05.932055 | 2017-05-02 18:13:25.343283 |               10 |                 11 |                12
 fruit.demo.hydrainabox.org           | 2017-05-02 23:32:12.773409 | 2017-05-02 23:32:27.281077 |               13 |                 14 |                15
 acme.demo.hydrainabox.org            | 2017-05-03 04:11:04.430945 | 2017-05-03 04:11:19.327859 |               16 |                 17 |                18
 ajs.demo.hydrainabox.org             | 2017-05-03 15:12:06.538236 | 2017-05-03 15:12:06.538236 |                  |                    |                  
 pear.demo.hydrainabox.org            | 2017-05-03 17:50:22.649465 | 2017-05-03 17:50:22.649465 |                  |                    |                  
 bbtesttenant.demo.hydrainabox.org    | 2017-05-03 18:51:09.438584 | 2017-05-03 18:51:09.438584 |                  |                    |                  
 gg.demo.hydrainabox.org              | 2017-05-03 19:54:05.947005 | 2017-05-03 19:54:05.947005 |                  |                    |                  
 ggstanford.demo.hydrainabox.org      | 2017-05-03 19:56:46.080639 | 2017-05-03 19:56:46.080639 |                  |                    |                  
 bbtesttenant2.demo.hydrainabox.org   | 2017-05-03 23:38:57.755706 | 2017-05-03 23:38:57.755706 |                  |                    |                  
 bbtesttenant3.demo.hydrainabox.org   | 2017-05-04 00:38:40.364392 | 2017-05-04 00:38:55.57752  |               19 |                 20 |                21
 testy.demo.hydrainabox.org           | 2017-05-04 16:20:04.262988 | 2017-05-04 16:20:19.483845 |               22 |                 23 |                24
(14 rows)
```

**Comment by mjgiarlo** [comment]
If ZK is broken, I might like to see account creation fail. Thoughts?

**Comment by atz** [comment]
@mjgiarlo: it did fail, in a sense.  Because an account must be persisted before its account creation job is called, there is no additional data constraint that would help here.  At the risk of repetition, it's almost like you want some kind of informative intermediate interface for the user during the critical account creation steps (or just after some/all of them have failed).

**Comment by cbeer** [comment]
From the description of the problem, I'm not sure it "failed" as much as it broke in unexpected ways. I suspect @mjgiarlo is suggesting we fail faster/harder. Perhaps we should lock tenants out of an account until all the endpoints are initialized?

**Comment by atz** [comment]
@cbeer so you propose an *uninformative* intermediate interface.

**Comment by atz** [comment]
@ggeisler I will shortly be deleting yours and the other malformed accounts to clean up the demo site.

**Comment by mjgiarlo** [comment]
@atz What @cbeer suggested could work:
> Perhaps we should lock tenants out of an account until all the endpoints are initialized?

**Comment by ggeisler** [comment]
Feel free to delete any of my repos @atz.

**Comment by randalldfloyd** [comment]
@atz No need to protect my repo to get this sorted out.

**Comment by atz** [comment]
OK, accounts cleaned up.  Hopefully that means we can close this?

**Comment by atz** [comment]
Let me know if you see the bleeding over again.

**Comment by ggeisler** [comment]
Just created a new repo and do not see any works in the default admin set, as expected, so my original problem certainly appears to be fixed.
