### ISSUE TITLE
Race conditions to destroy endpoints?

### ISSUE THREAD

**Issue by darrenleeweber** [projecthydra-labs/hyku#1068]
These two lines both destroy an fcrepo_endpoint, which one wins?
- https://github.com/projecthydra-labs/hyku/blob/master/app/jobs/cleanup_account_job.rb#L22
- https://github.com/projecthydra-labs/hyku/blob/master/app/models/account.rb#L35

Likewise for Solr, which one wins?
- https://github.com/projecthydra-labs/hyku/blob/master/app/jobs/cleanup_account_job.rb#L44
- https://github.com/projecthydra-labs/hyku/blob/master/app/models/account.rb#L34 (edited)

Are there race conditions to destroy the dependent endpoints on an account when the account is destroyed?

There seems to be no `Account#destroy` specs in https://github.com/projecthydra-labs/hyku/blob/master/spec/models/account_spec.rb

There seems to be no `before_destroy` or something on the Account that makes a synchronous call to the BG-job for doing the cleanup(s).

**Comment by darrenleeweber** [comment]
There are 3 silent points of failure in `CleanupAccountJob`:
- https://github.com/projecthydra-labs/hyku/blob/master/app/jobs/cleanup_account_job.rb#L19
- https://github.com/projecthydra-labs/hyku/blob/master/app/jobs/cleanup_account_job.rb#L27
- https://github.com/projecthydra-labs/hyku/blob/master/app/jobs/cleanup_account_job.rb#L41

Possibly, these should raise exceptions and crash, or at least notify HoneyBadger?

**Comment by atz** [comment]
In some sense, it doesn't matter which part deletes them.  But as a practical matter, we expect that `@account.destroy` would be the last thing getting called, since account data is required for the jobs.  

According to these docs: http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to

```
:dependent
If set to :destroy, the associated object is destroyed when this object is. If set to :delete, the associated object is deleted without calling its destroy method.
```
So the associated `Endpoint` object should never get a destroy call from rails (we are using `:delete`).  

In SQL (as opposed to, say, `rm`), it's not a failure to delete a row that isn't there: `DELETE from mytable WHERE id=3`.  The only expectation is that no row matching the WHERE clause will be there for the next query.

**Comment by darrenleeweber** [comment]
An alternative approach is to have all the background jobs for each endpoint kicked off by a `before_destroy` on each of the endpoint models (so maybe that entails using a cascade destroy instead of cascade delete on the account model).

As is, there might be scenarios where it is possible to have orphaned Solr-collections or Fcrepo-containers, as in say console access to `Account.find('name').destroy` (or something like that).

**Comment by atz** [comment]
While it would be more rails-idiomatic, the async nature of jobs means that the `before`-ness is not guaranteed.  Therefore that hook is questionable.

**Comment by darrenleeweber** [comment]
@cbeer and @atz noted in standup discussions today that the intention is to have loose coupling between the rails model for the account and the endpoints and the actual services.  The rails integration with a SQL-db is not the same integration to be expected for Solr, Fcrepo, and Redis.

Note that the project github wiki has some documents explaining how to identify and cleanup orphaned Solr, Fcrepo collections or add these services to an account that is missing these essential connections.  So the loose coupling does result in some "broken" accounts that may require manual intervention to patch.

**Comment by cbeer** [comment]
Indeed. And a failure scenario where orphaned data sits around should be easy to detect and write tooling for if and when it would be helpful to administrators. Right now, I don't think we have a good understanding of the tooling or workflows for normal operations (although the beta/pilots should help clarify that).
