### ISSUE TITLE
Solr connection - memoize?

### ISSUE THREAD

**Issue by darrenleeweber** [projecthydra-labs/hyku#1072]
https://github.com/projecthydra-labs/hyku/blob/master/app/models/solr_endpoint.rb#L8
- calls `RSolr.connection()` every time
  - does `RSolr` handle all the connection management details efficiently (or does it expect the caller to be smart about managing the connections)?
  - is `RSolr.connection()` idempotent (when all the options are the same)?
  - should it be memoized?

**Comment by cbeer** [comment]
No need. Connections are stateless and cheap to create.
