### ISSUE TITLE
Travis before_deploy could use `git archive`?

### ISSUE THREAD

**Issue by darrenleeweber** [projecthydra-labs/hyku#1073]
```yaml
before_deploy:
  - git clean -dxf; rm -rf vendor/bundle
  - echo ${TRAVIS_COMMIT} > REVISION
  - mkdir -p build
  - git archive --format=zip --output=build/hyku.zip ${TRAVIS_BRANCH}
```
This allows git to take care of what to include/exclude.  This might leave out the `REVISION ` file, but the docs on `git archive` indicate that it automatically adds comments into the zip archive to track the commit.  Another way to get a REVISION file is to add a git hook to have it auto-update and include it in the repo.

**Comment by cbeer** [comment]
What we're doing now seems to work; Is there a compelling reason to do something different?

**Comment by darrenleeweber** [comment]
No, if the current zip file doesn't contain too much extraneous details, it's OK.  Maybe the `.git` directory is one difference between these options?  (Feel free to close this out if it doesn't matter; I can't think of an easy way to get a clean diff of the results, only manual review of the `zip -l` contents for them.)
