### ISSUE TITLE
travis.ci caching for solr_wrapper and fcrepo_wrapper downloads

### ISSUE THREAD

**Issue by darrenleeweber** [projecthydra-labs/hyku#1085]
travis.ci would run faster with a cache for the solr_wrapper and fcrepo_wrapper downloads.  They seem to take a few mins to download, e.g.

```
solr-6.5.1.zip: |=======================================| 100% (Time: 00:00:24 )
solr-6.5.1.zip.md5: |===================================| 100% (Time: 00:00:00 )
fcrepo-webapp-4.7.1-jetty-console.jar: |================| 100% (Time: 00:01:51 )
fcrepo-webapp-4.7.1-jetty-console.jar.md5: |============| 100% (Time: 00:00:00 )
```

I don’t see anything in the `.travis.yml` or the `rake ci` task to set the download directory to something that can be cached on travis.

**Comment by cbeer** [comment]
Travis’ caching documentation states:

> Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source. (https://docs.travis-ci.com/user/caching/#Things-not-to-cache)

and, anecdotally, that’s been true in the past.

**Comment by darrenleeweber** [comment]
This was tested in https://travis-ci.org/projecthydra-labs/hyku/builds/230513807?utm_source=github_status&utm_medium=notification

The `rake` specs no longer had any download activity in the logs for solr_wrapper and fcrepo_wrapper.  The cached downloads seem to be restored within seconds, going by the screenshot attached.  The raw log did not have any timing details in it.

![travis-cache-solr_fcrepo-2017-05-09 13-44-53](https://cloud.githubusercontent.com/assets/240623/25872067/46838ffc-34be-11e7-825f-4b007573c8fe.png)

In total, the build `Ran for 6 min 46 sec`.  That was not substantially faster that a few prior passing builds on that branch, although one prior build took 10+ mins.

**Comment by cbeer** [comment]
That timing seems well within the margin of error compared to our other builds?

**Comment by darrenleeweber** [comment]
Yes, the total build time was in the usual ballpark.  So, if that's representative, it doesn't make much, if any, difference to cache the Solr/Fcrepo downloads.  Pity.

**Comment by mjgiarlo** [comment]
@darrenleeweber Good experiment, though!

**Comment by jrochkind** [comment]
I cache em to avoid the rate limits from downloading solr archives anyway, on my project. And just seems polite to the archive hoster.
