### ISSUE TITLE
Manager of an admin set does not see works deposited to the admin set on the Works page

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#1111]
### Expected behavior

I am a Manager of the default admin set. When I am on the dashboard, I expect to see any works deposited to that admin set listed on the Works page, under the Repository Contents. 

I expect to see works that have been submitted after the time I was granted the role of Manager

I expect to see works that have been submitted, regardless of whether they are in active or not in active workflow.

### Actual behavior

My works page is blank.

![screenshot 2017-05-12 09 20 55](https://cloud.githubusercontent.com/assets/1801076/26007306/c0299472-36f4-11e7-9a7a-a8089bdb15f2.png)

Related to https://github.com/projecthydra-labs/hyrax/issues/853

**Comment by jcoyne** [comment]
@hannahfrost this seems just like #855, but "as an admin set manager" instead of "as a repository administrator". Is that correct?

**Comment by jcoyne** [comment]
@hannahfrost is there some reason this is in hyku and not hyrax? 

Additionally, should an "admin set manager" get the "All works" tab on this page? https://github.com/projecthydra-labs/hyku/issues/447#issuecomment-276233397 just like the repository manager has?   Is "All works" going to be confusing?

**Comment by hannahfrost** [comment]
@ggeisler See @jcoyne 's comment above. The question is what should appear on an admin set Manager's Works page? This Manager may not be able to see All Works in the repository, and may not have any works of their own to see. Do they get a different tab?

**Comment by ggeisler** [comment]
@hannahfrost @jcoyne Yeah, I see the issue. Maybe a third tab is the right approach?

* All Works - for repository manager - everything in the repository
* Managed Works - all works the user can manage by virtue of being an admin set manager for one or more admin sets
* Your Works - works deposited by or shared with the user

**Comment by mjgiarlo** [comment]
Copied to https://github.com/projecthydra-labs/hyrax/issues/965. Pls continue discussion over there. Thanks!
