### ISSUE TITLE
Upgrade to active-elastic-job 2.0

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#1129]
This will involve several steps:

1. Add the new environment variable `PROCESS_ACTIVE_ELASTIC_JOBS` to https://github.com/hybox/aws/blob/bd95b91c569ccb931abf33a321dc77a04933969e/templates/worker.yaml
1. Update the Gemfile and bundle install
1. Remove the old `DISABLE_SQS_CONSUMER` variable: https://github.com/hybox/aws/blob/bd95b91c569ccb931abf33a321dc77a04933969e/templates/webapp.yaml#L315-L317

**Comment by mjgiarlo** [comment]
:tada: @cbeer @jcoyne
