### ISSUE TITLE
Uploads shows s3 url rather than file name

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#201]
<img width="817" alt="screen shot 2016-05-24 at 11 27 13 am" src="https://cloud.githubusercontent.com/assets/92044/15511758/8d80ac08-21a2-11e6-9f92-a50a8fddf347.png">

**Comment by atz** [comment]
Fixed:
<img width="758" alt="screen shot 2017-04-14 at 12 33 30 pm" src="https://cloud.githubusercontent.com/assets/109954/25053998/9a14c3c4-210f-11e7-9d4b-bfd58383313a.png">

**Comment by jcoyne** [comment]
🥂 👏 🎊
