### ISSUE TITLE
UI customization: color theming

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#286]
As a repository admin, I need to change the main color(s) via the settings UI, so that I can easily customize the look of my repository.

**Comment by jcoyne** [comment]
The main colors of which elements?

**Comment by hannahfrost** [comment]
@jcoyne Colors of fonts used in header, nav bar, maybe facet labels too. Background color of main/home header if no image is used.

**Comment by jcoyne** [comment]
Okay, can we say this ticket is complete when?

- [ ] An repository admin can set the color of the header font ("Hydra-in-box" in the example below)
- [ ] An repository admin can set the color of the nav bar font ("Home", "About", "Help" in the example)
- [ ] A repository admin can set the color of facet label font ("Creator" in the example)
- [ ] A repository admin can set the background color of the root page header (Where the image of flowers is on this page: https://baz.demo.hydrainabox.org/)

<img width="702" alt="screen shot 2016-08-09 at 9 00 37 am" src="https://cloud.githubusercontent.com/assets/92044/17519171/623effe0-5e10-11e6-838d-ddbdc490964f.png">

**Comment by hannahfrost** [comment]
@jcoyne OK. List looks good. I omitted the piece about setting background color, so it'll support background image only, but in that case, now I'm wondering if we should provide multiple default photo options (lilies, roses, etc.) so multiple tenants can look different without be forced to provide their own images.

**Comment by jcoyne** [comment]
- [ ] and there should be lilies
- [ ] and there are roses

**Comment by mjgiarlo** [comment]
I believe we've backburnered this ticket to post-MVP.

**Comment by jcoyne** [comment]
I'd like to bump the priority of this ticket.  I'd like to get it done for OR.

**Comment by hannahfrost** [comment]
OK

**Comment by hannahfrost** [comment]
I think we can close this ticket now. The configuration options now available under the Appearance settings address this need.
