### ISSUE TITLE
Add a rightsstatements.org assertion as "rights"

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#293]
- [ ] in copyright
- [ ] no copyright
- [ ] other

Move the existing "rights" to be "license".  Only show the existing CC licenses if they select "in copyright"

**Comment by mjgiarlo** [comment]
:+1: Should we make this change down in a lower layer? If needed, we can propose on Hydra Tech tomorrow.

**Comment by jcoyne** [comment]
@mjgiarlo yes, I want to try to push this into cc or sufia.

**Comment by mjgiarlo** [comment]
@jcoyne Is this still in progress or should we update this issue?

**Comment by jcoyne** [comment]
I'm not working on it ATM.  The property is in CC and it's ready to proceed to the UI layer now.
