### ISSUE TITLE
[HyBox/production] ActionController::UrlGenerationError: No route matches {:action=>"index", :controller=>"sufia/homepage"}

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#351]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/31104965)

**Comment by jcoyne** [comment]
This still appears to be an issue.  It seems to occur, when solr gets a 404 on the generic_work show page. Then ` [GEM_ROOT]/gems/blacklight-6.7.1/app/controllers/concerns/blacklight/base.rb:37 :in 'handle_request_error' `  tries to create a poorly formed route:

**Comment by jcoyne** [comment]
This is probably fixed in https://github.com/projectblacklight/blacklight/commit/2afeb7707a78a758eb091310971ec959761cc45d, but that's BL 7. We should backport a fix for BL 6.
