### ISSUE TITLE
[HyBox/production] PG::UnableToSend: SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#394]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/31326503)

**Comment by jcoyne** [comment]
@cbeer what is calling, is_it_working? Is that a load balancer? Do you think this was an ephemeral fault?

**Comment by cbeer** [comment]
Yes, the ELB calls `is_it_working`, and, yes, presumably ephemeral.
