### ISSUE TITLE
add "visibility" to the admin set form

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#419]

**Comment by mjgiarlo** [comment]
Work on this in Sufia.

**Comment by hannahfrost** [comment]
@tdonohue Regarding your question about the possibility of a "private" admin set - yes, please do add private as a fourth option below "Institution" on the list under "Visibility". @ggeisler will weigh in on exact wording.

**Comment by ggeisler** [comment]
Here's the updated form design, with the additional option to cover the "private" or dark archive case showing last in the Visibility section (we're calling it "Restricted" unless/until we think of a better way to characterize it):

![admin-set-r now-v restricted](https://cloud.githubusercontent.com/assets/101482/19938996/4d474644-a0e4-11e6-9c7a-e8b3b14d1781.png)

**Comment by tdonohue** [comment]
Fixed by  projecthydra/sufia#2857
