### ISSUE TITLE
Repository Activity Summary

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#431]
Shows the repository manager highlights of repository activity in an easy-to-digest format.
## Mockup

I suggest we refine the details of this page as the project evolves, as we better understand what sort of statistics we have available and which seem best for this page, versus a regular report.

This might be a good start. Not clear whether the Collections table should list admin sets or some other type of collection. We can revisit after we resolve the question of whether collections are needed or not (separate from renaming "administrative sets" to "collections").

![repository-activity](https://cloud.githubusercontent.com/assets/101482/19822504/ab699904-9d18-11e6-98f0-56fe4ce1ebdf.png)
- Repository Growth graph shows number of works and number of collections/admin sets.
- Repository Contents graph shows published and unpublished works. Are those the most useful attributes to display? Are there other states?

**Comment by hannahfrost** [comment]
Looks good, Gary.

**Comment by jcoyne** [comment]
We don't have many of these metrics, so this ticket should probably be decomposed into "Collect metrics for ..." and "Display metrics for ..." for each panel.

**Comment by jcoyne** [comment]
I'm not sure it's possible to count files within admin sets (collections on this mockup). Since, we don't directly associate files to admin sets and since works can be nested, and each work could have a different admin set, it's not possible to say which admin set a file belongs to.

**Comment by ggeisler** [comment]
Okay, we can leave off the Files column and just go with counts of Works. I'm sure details of these blocks will change over time as we figure what data is most feasible to gather and useful to display in this context.

**Comment by jeremyf** [comment]
One mechanism we are using is collecting metrics via a separate tiny Rails application:

1) Crawl the web server logs for access
2) Iterate through Fedora for the object information

We are in the process of building out reports for this. https://github.com/ndlib/hesburgh_metrics 

Its built via nightly jobs.

**Comment by jcoyne** [comment]
This seems like it's ready to be closed ("design complete"). We should then create new tickets for exposing each component on the admin page.

**Comment by ggeisler** [comment]
I did finish an initial design that seems good enough to start development on. I do want to point out that @hannahfrost mentioned to me yesterday that she, @mjgiarlo, and Steven from OSU have recently been working on a Google Doc related to Google Analytics that I think could add some elements to this design. 

I'm not sure they're done with that document, and I won't have time immediately to translate their requirements into this design, so I don't suggest **not** working on this design, but be aware that there might be additional elements added in the future based on forthcoming requirements.
