### ISSUE TITLE
Configuration > Settings > Content Blocks

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#440]
## Preliminary Mockups

https://docs.google.com/document/d/1WZIOL8omCseweV6OSP65SkSQCxtoXbtP65UVN9doBPY/edit#heading=h.4cnihetzl8p4

**Comment by hannahfrost** [comment]
Reviewed, looks good. I do have one suggestion for the Featured Researcher content block. See comments in the doc and let's discuss.

**Comment by ggeisler** [comment]
@hannahfrost I've left the Featured Researcher block as is for now, since this ticket is intended as more of a short-term enhancement. Longer-term I'll figure out how to deal with making the Featured Researcher text more generic (or offer alternatives so a given repository could omit Featured Researcher and use another block instead). That strategy will be part of #457
