### ISSUE TITLE
Configuration > Manage Users

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#444]
From the [Administrative Dashboard Needs document](https://docs.google.com/document/d/1Hcn0fjVEkhvwUxcdJbBFWo1IKo9SphMLiwVM1VYYrR4):

> **Add** and remove users from repository roles as needed, so that I can maintain a current repository user base with appropriate permissions levels.
> 
> **Search for a user by name** and edit its repository role(s), across one or more admin sets, as needed, so that I can maintain a current repository user base with appropriate permissions levels.
> 
> **See a list of users in the role of admin set manager** and the linked names of admin sets that they each manage.

@hannahfrost When we next have time to discuss, here's a link to proposed ideas for this ticket: https://docs.google.com/document/d/1opkc-KA6nNMu6tuJQ_NlbvoWvSqIsGcyezuGMGVyJqQ/edit#

**Comment by hannahfrost** [comment]
Reviewed and commented. Ready for some discussion.

**Comment by ggeisler** [comment]
## Mockups

### Manage Users option

Only users in the **repository administrator** or **repository manager** roles can manage other users, so only users in those roles see the User and Groups menu item. First step is selecting the Manage Users option in the admin sidebar. 

![sidebar-manage-users](https://cloud.githubusercontent.com/assets/101482/20907158/ca320a7e-bb09-11e6-8a04-533c6879be53.png)

### Manage Users page
The Manage Users option displays this page:

![manage-users-roles](https://cloud.githubusercontent.com/assets/101482/20907182/edf68dd6-bb09-11e6-872b-4ec63c7601eb.png)

This is an enhanced version of the current users table. The major update is the Roles column, intended to satisfy the expressed user need that the repo admin can see a list of users with the role of admin set manager (the search box would also satisfy that need). The idea is that if the user is either a Repository Administrator, Repository Manager, or Administrative Set Administrator that role is shown and there is no need to show any other role for that user (since those global roles encompass privileges of all lesser roles). Otherwise, show each unique role that the user has been assigned.

I’m not sure if this idea for the Roles column would require a prohibitive number of queries. If so, we can discuss an alternative approach.

Clicking the linked username leads to the Edit User Roles page (mockup below). This is a datatable, so columns are sortable and the Search box enables the user to quickly filter by name, role, department, etc.

### Edit User Roles
When the admin or manager selects a user from the Manage Users table, it leads to the page mocked up below. This is a new page, distinct from the existing User Profile page. The rationale for a distinct page is that this page can be tailored to the likely goals of the repository administrator when investigating a user, which overlap with but are different than what a normal user would see when viewing his own or another user’s profile page.

![edit-user-roles](https://cloud.githubusercontent.com/assets/101482/20907201/09cf004c-bb0a-11e6-9707-5d53326f867e.png)

A handful of sections are shown on this page:

* **Repository Activity** - The linked item counts for the Admin sets, Works deposited, etc. lead to the Admin sets, Works, etc. index page, filtered by the user being viewed (i.e., view the list of 33 works deposited by username “gutinl@stanford.edu” in the previous mockup).

* **Repository Roles** - this is where a user can be assigned one of the global (repository-wide) roles of repository administrator, repository manager, or administrative set administrator. Only one role can be selected, and the default value is None.

![repo-roles](https://cloud.githubusercontent.com/assets/101482/20907222/31c14cea-bb0a-11e6-9a47-ff7098d65879.png)

* Since only Repository Administrators should be able to make other users a Repository Administrator, if the current user is a Repository Manager, the Repository Administrator option should not be shown:

![repo-role-no-admin](https://cloud.githubusercontent.com/assets/101482/20907236/44e76a34-bb0a-11e6-88a8-825a990443f0.png)

(Edge case: if the current user is a Repository Manager, they should not be able to access the Edit Roles page of a Repository Administrator user, because they shouldn't have the power to downgrade the role of, or deactivate, a user with higher privileges than themself.)

* **Proxies** - Show usernames of all proxies the user has designated. If the user has not designated any proxies, show the Proxies heading but with the italicized text: “No designated proxies”

![no-proxies](https://cloud.githubusercontent.com/assets/101482/20907262/5c5d06b0-bb0a-11e6-8ae7-9ed09b42109a.png)

* **Administrative Set Roles** - The “edit role” links in the Actions column for admin sets should lead to the Participants tab of the relevant Edit Administrative Set page.

* **“View user profile” button** - Leads to the user’s profile page. 

* **“Deactivate user” button** - The concept of a deactivated user is new and will require a separate ticket to document the ramifications, but for the purposes of this ticket it means a user can be changed from a normal, active state to a deactivated state using the button at the top right of the main content area.

Clicking the “Deactivate user” button displays a confirmation popup with the text “Are you sure you want to deactivate this user? The user’s data will remain in the repository but the user will no longer be able to manage content in the repository.” The popup should also show the “Cancel” and “OK” buttons that are usual in a confirmation popup.

If the user confirms the popup:
- Change the user’s state to “deactivated”
- Return to the Manage Users index page
- Display a flash message confirmation:

![flash-message](https://cloud.githubusercontent.com/assets/101482/20907290/8a196652-bb0a-11e6-8e2c-ba74915af511.png)

* Viewing the Edit User Roles page for a deactivated user - If the user being viewed is already in a deactivated state, show the top right button with the label “Activate user”:

![activate-user](https://cloud.githubusercontent.com/assets/101482/20907295/97c86a82-bb0a-11e6-9ed6-86cf0dac4385.png)

**Comment by jcoyne** [comment]
This ticket should be closed ("design complete"). And new tickets should be created to build out these functions in the site.  One concern I have is that "administrative set administrator" is going to be confused with "administrative set manager" (person with manage role on a particular admin set).

**Comment by ggeisler** [comment]
Yes, @hannahfrost and I have the same concern about "Administrative set administrator." However, I think there is a desire to replace the term "administrative set" with something more user-friendly after we figure out the relationship between collections, display sets, admin sets, etc. So if and when we have a new term for "administrative set" we will revisit the role labels and change this to something less cumbersome.
