### ISSUE TITLE
fcrepo fails to start with docker-compose

### ISSUE THREAD

**Issue by novomancy** [projecthydra-labs/hyku#458]
I'm trying to use docker to run Lerna locally. Immediately after running `docker-compose up -d` I'll get a 503 error if I try to load a page. It appears that lerna_fcrepo_1 isn't starting, or is failing on startup with an exit 1. Going through the logs, the only line referring to that was this:

`fcrepo_1          | Error: Could not find or load main class  -Dfcrepo.modeshape.configuration="classpath:.config.minimal-default.repository.json"`

Not sure what caused it, but removing and rebuilding the images doesn't seem to help.

**Comment by mjgiarlo** [comment]
Thanks for testing this, @novomancy! Any ideas, @cbeer?

**Comment by cbeer** [comment]
No, I haven't seen anything about this before. Can you let me know what version of docker etc you're running?

**Comment by novomancy** [comment]
Docker:
`Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64`

docker-compose:
`docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9`

cbeer/fcrepo4 just lists its version as latest.

Output from the build is attached. Note that lerna_web_1 and lerna_workers_1 are also failing now; they weren't when I was trying this earlier. This is a new install of Docker.

[lerna_docker_setup.txt](https://github.com/projecthydra-labs/lerna/files/567935/lerna_docker_setup.txt)

**Comment by seanlw** [comment]
I'm seeing the same issues with lerna_fcrepo_1 not starting up. Gives the same error mentioned above 

`Error: Could not find or load main class  -Dfcrepo.modeshape.configuration="classpath:.config.minimal-default.repository.json"`.

The web interface starts up and I can get to the splash page and can even create a account. However, anything after that, going to Admin or create a work, takes me back to the splash page.

Docker version 1.12.1, build 6f9534c
docker-compose version 1.8.0, build f3628c7
Mac OS 10.12.1
Git SHA1: 3f04860d695c99743c6d2309888b3dfa162f4828

**Comment by caleno** [comment]
The problem on my end was the environment variable JAVA_OPS which was not properly set in the container. I had to set the JAVA_OPS variable in may shell (on my host) and refer to it in the composer file before starting it (in the same shell). But I don't get very far on trying out the app, only a 404 message about the page missing. "The page you were looking for doesn't exist." Anyone got the docker stack up en running atm? 

#~ export JAVA_OPTS="-Dfcrepo.modeshape.configuration=classpath:/config/minimal-default/repository.json"

docker-compose.yml
```
...
  fcrepo:
    image: cbeer/fcrepo4
    expose:
      - 8983
    volumes:
      - fcrepo:/data
    environment:
      - JAVA_OPTS
    networks:
      internal:
...
```

**Comment by mjgiarlo** [comment]
Thanks for looking into this, @caleno!

**Comment by pbinkley** [comment]
I'm having the same problem with missing pages: /splash and /users/sign_in exist, along with their assets, but /dashboard , /admin, other /users pages, /collections etc. don't.

**Comment by atz** [comment]
JAVA_OPTS line is here: https://github.com/projecthydra-labs/hyku/blob/master/docker-compose.yml#L93

But it sounds like whatever java command docker is assembling, like `$JAVA_EXEC $JAVA_OPTS $JAVA_CLASS` is not receiving a $JAVA_CLASS to target.  That's why it thinks the main class is `-Dfcrepo.modeshape.configuration="classpath:.config.minimal-default.repository.json"`
