### ISSUE TITLE
Specify how one configures Google Analytics for their repo

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#460]
In order to design a mockup for configuring Google Analytics, must know what are GA's requirements. 

- Enter tracking ID
- Enter Javascript snippet

Is that it? Something else?

**Comment by mjgiarlo** [comment]
There are two sections here with different steps: https://github.com/projecthydra/sufia/wiki/Sufia-Management-Guide#analytics-and-usage-statistics

On mobile now, so I'll follow up tomorrow.

**Comment by jcoyne** [comment]
@hannahfrost I don't think we should assign tickets to people without their agreement. Ok?

**Comment by hannahfrost** [comment]
Oh, OK! I was remembering that you had been dealing with GA in Lerna before, that was why I thought of you. No problem.

**Comment by jcoyne** [comment]
@hannahfrost I'm sure I could do this, but, I'm not sure that I have any specialized knowledge in this area that any other engineer/devops type doesn't have.  If you assign a ticket to me, it may prevent someone else from picking it up.

**Comment by mjgiarlo** [comment]
@hannahfrost @jcoyne @ggeisler We have a decision to make here: are we OK with having stats for all tenants gathered by a single GA account? This direction is simpler because we're using what Sufia already provides. If we want to have each tenant use their own GA account -- which gives tenant owners more access to their data at the cost of needing to know how to navigate Google's labyrinthine websites -- we'll need to do some development.

**Comment by ggeisler** [comment]
It might help if we have a couple of concrete examples of multi-tenant scenarios we can use to think about what makes the most sense for the users in those scenarios.

Do we have any user stories developed that describe expected multi-tenant scenarios? I think the Tri­College Library Consortium might be one?

**Comment by mjgiarlo** [comment]
@ggeisler Good call. I'm thinking of the hosted service, I suppose.

**Comment by ggeisler** [comment]
Right. But unless we're developing a feature for only the hosted service, I think it's useful to consider all the main scenarios, so we don't make decisions just based on one or the other. 

Then again, if we think the hosted service is our primary use case for adopters, then thinking from that point of view might be enough. I guess I'm fuzzy on our business strategy in terms of what adopter scenarios we're focusing on.

**Comment by mjgiarlo** [comment]
I completely agree, @ggeisler. The hosted service is not our primary use case, IMO.

**Comment by hannahfrost** [comment]
@ggeisler @mjgiarlo  Right, the hosted service and multitenancy complicates it. I'd still like to see any easy configuration for GA in the UI for use in non-multitenancy scenarios (e.g., Dartmouth puts HyBox in their AWS for their use.)  

In the hosted context, I do not think it is not acceptable to mix analytics of customers who are not formally partnering in some way (like a consortium). I guess in those cases, GA would not be enabled on the host end OR the host would need to develop a way of filtering the analytics of a multitenent site by customer separately. Does that seem possible, at least technically?

I wonder if/how DSpaceDirect deals with this. @bbranan or @tdonohue - do you know?

**Comment by bbranan** [comment]
DSpaceDirect deals with this by not being a multitenant application. Each customer gets their own install of DSpace, so there's no potential for mixing.

In the hosted HyBox scenario, as you said Hannah, we need to either make this something that is not available at all (in the case where the GA data covers all accounts), or do the development necessary to break it out per tenant.

**Comment by tdonohue** [comment]
For a Hybox hosted service, personally, I'd recommend seriously considering making the GA key/ID configurable from the Admin UI settings per tenant (like the site name, landing page image, etc).

With DSpaceDirect, I find that most customers already have a GA account, and they want their repository stats to feed into that existing account (or a sub-account of it). We have very few customers that do *not* use/enable GA immediately.

**Comment by hannahfrost** [comment]
@tdonohue @bbranan Thanks for your input. I agree with your assessment

**Comment by hannahfrost** [comment]
Circling back to this finally, I've got user stories in progress here: https://docs.google.com/document/d/1FmCAxVuOn9e9UyL15BsS1PUqyJX96kgTuA22Lqiukpw/edit#. As I further refine them before turning them over to Gary for design, I'd welcome feedback from the technical team. @mjgiarlo for starters

**Comment by mjgiarlo** [comment]
Looking good, @hannahfrost! Care to review this before it moves on to design, @jcoyne?

**Comment by mjgiarlo** [comment]
@hannahfrost OK, I believe we've answered the question in this issue. Inclined to close and do analytics work in #252 and #438. If those two issues aren't sufficient to turn the GA cell in the MVP column in the feature matrix green, we'll need to write up more tickets.
