### ISSUE TITLE
[HyBox/production] ActionView::Template::Error: undefined method `/concern/generic_works/3484zg88m_url' for #<#<Class:0x0055f286e299a0>:0x0055f285ea1140>

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#465]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/31677020)

**Comment by jcoyne** [comment]
Should be fixed by https://github.com/projecthydra/curation_concerns/pull/1082
