### ISSUE TITLE
[HyBox/production] Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#466]
## Backtrace

    line 25 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in perform_now
    line 41 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in switch
    line 40 of [PROJECT_ROOT]/lib/active_job_tenant.rb: switch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/31707300)

**Comment by jcoyne** [comment]
This is now causing #430

**Comment by jcoyne** [comment]
Fixed by #473
