### ISSUE TITLE
Rename "Roles and permissions" admin sidebar menu item

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#483]
Since there doesn't seem to be a need for a Roles and permissions page at the general repository level, we should:

- [x]  Rename the "Roles and permissions" menu item to "Users and groups"

- [x]  Add a "Manage groups" menu item within that category

- [x]  Remove the "Define roles and permissions" menu item that is currently there

So things would look like this:

![users-groups](https://cloud.githubusercontent.com/assets/101482/20362321/f1da3890-abef-11e6-98c2-5e7ae7b2dfe0.png)

**Comment by andjsmit** [comment]
Is the "Manage groups" an existing page (the current Define roles... ?) or  does it need to be created for this issue?

**Comment by andjsmit** [comment]
Looks like the answer to above is page does not yet exists. This issue appears to be tied to #421.

**Comment by mjgiarlo** [comment]
I think you've got it. Thanks, @andjsmit!

**Comment by laritakr** [comment]
Waiting on issue #421 to add the new "Manage groups" menu item.
