### ISSUE TITLE
Sidebar collapsible menu only halfway remembers the current page

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyku#491]
After clicking sidebar menu navigation for a link *below* the top level, it has the nav-button highlighted… but then it also collapses the top level nav-category so that you can’t see it.

When I go to `http://localhost:3000/admin/users`, it should expand the “Roles and permissions” group that the current address is linked from (showing "Manage Users” highlighted).  It currently does the highlight, but not the expansion.

**Comment by jcoyne** [comment]
Fixed in https://github.com/projecthydra-labs/hyku/pull/515
