### ISSUE TITLE
Reroute to missing show page on access error

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyku#495]
Exception on non-ACL'd user accessing admin_set edit page.  CANCAN 500 error tries to reroute to "show" page, but no such route exists.

Exception is upon viewing, e.g. http://localhost:3000/admin/admin_sets/4m90dv48q/edit :
```
ActionController::UrlGenerationError in Sufia::Admin::AdminSetsController#edit
No route matches {:action=>"show", :controller=>"sufia/admin/admin_sets", :id=>"4m90dv48q"}
```

That is preceded by:
```
[CANCAN] Checking edit permissions for user: x@y.com with groups: ["public", "registered"]
[CANCAN] edit_groups: ["admin"]
[CANCAN] edit_users: []
[CANCAN] decision: false
Completed 500 Internal Server Error in 92ms (ActiveRecord: 1.5ms)
```

**Comment by jcoyne** [comment]
@atz I can't reproduce this.  Is it fixed?

**Comment by atz** [comment]
Yes, confirmed fixed.  Now shows: `You do not have sufficient privileges to edit this document`
