### ISSUE TITLE
Selection on New Work type modal needs adjustment

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#496]
The name of each work type listed on the “Select type of work” modal should not be clickable. Instead each item on the list should be selectable, like a radio button list, and the user should click the “create work” button to trigger loading the “Add New Work” page

**Comment by ggeisler** [comment]
The mockup and explanation in https://github.com/projecthydra/sufia/issues/2434 might help clarify the difference between the current implementation and the intended design.

**Comment by atz** [comment]
So this is why the "Create Work" button currently does nothing.

**Comment by atz** [comment]
I don't understand the semantics of multiple selections in this context.  Not all models are compatible with one another, so:
- a user cannot necessarily create a batch of hybrid `model1/model2`s.  
- a user cannot create (via the same form) a batch of objects that are "either `model1` or `model2`".  
- They can create a batch of a **given** model, specifically one that we can deliver the form for on the next page.

Therefore I only see a single selection being relevant here.  Do I misunderstand the scenario or are you forgetting a fundamental limitation of the platform?

**Comment by atz** [comment]
This probably should not be a Hyku ticket, since it affects features only and already in Sufia.

**Comment by mjgiarlo** [comment]
It's OK for this to start off as a Hyku ticket; we may want to also create an accompanying (appropriately decomposed if necessary) ticket in Sufia. Well, probably Hyrax, since that's what Hyku is using now.

**Comment by hannahfrost** [comment]
@atz Just to be clear, this ticket is not about batches of works. But in either case - single or batch work modal - the requirements are the same. The user selects the kind of work (thus indicating the required model) -- just one selection -- and then clicks the blue button, which takes them to the page where the single/batch creation work actually happens. 

If the user are batch creating, then each work in the batch must be all generic works or all image works (so far). This constraint is currently implicit, AFAIK. We can address that.

**Comment by atz** [comment]
The operating consensus on https://github.com/projecthydra/sufia/issues/2913 was that the same modal would be reused for both, making this ticket relevant to the batch context.

**Comment by hannahfrost** [comment]
After discussions on the relative complexity of implementing this modal, we're going for a different design.
