### ISSUE TITLE
thumbnail generation (or display?) is not reliable

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#500]
A thumbnail never did appear for my "Easter on Pillow Road" work. I played around with reassigning the designation to other files in the work, but no dice. Don't know if it is a generation or display issue. Another work created on the same afternoon had no thumbnail issues.

![screenshot 2016-11-22 17 19 27](https://cloud.githubusercontent.com/assets/1801076/20548383/d87e7608-b0d7-11e6-9665-886cfd2f1e21.png)

**Comment by jcoyne** [comment]
Can you show me the URL of the image in question?

**Comment by hannahfrost** [comment]
Here it is @jcoyne : https://tday.demo.hydrainabox.org/concern/images/zg64tk92g

**Comment by jcoyne** [comment]
"thumbnail_path_ss" seems to be indexed inconsistently.

**Comment by hannahfrost** [comment]
@jcoyne In my preliminary testing this morning, the image thumbnails are working, but thumb for a .doc file did not. Is this related to this issue or something separate?

**Comment by jcoyne** [comment]
@hannahfrost that's a separate issue. If you could add some description to #526 that would be swell.
