### ISSUE TITLE
My image work should display to me even if user collection is private.

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#501]
I have an image work (marked public) in a user collection (marked private). 

After navigating to my image work from my dashboard, I would expect to see the image files presented in the image viewer, below the work title and above all the other information, but the space is empty. 
![screenshot 2016-11-22 17 24 23](https://cloud.githubusercontent.com/assets/1801076/20548502/d96fdde4-b0d8-11e6-919c-964896bb3da0.png)

After I change the visibility on the user collection (now marked public), the image viewer displays to me.
![screenshot 2016-11-22 17 31 44](https://cloud.githubusercontent.com/assets/1801076/20548583/9a65b6f4-b0d9-11e6-8041-9eed2cd11e46.png)

**Comment by jcoyne** [comment]
Blocked by #519.

**Comment by jcoyne** [comment]
Unblocked.
