### ISSUE TITLE
[HyBox/production] ActionView::Template::Error: undefined method `uploaded_file_path' for #<ActionDispatch::Routing::RoutesProxy:0x00561dfc7227c8>

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#519]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/31938684)

**Comment by jcoyne** [comment]
Same as https://github.com/projecthydra-labs/hyrax/issues/12
