### ISSUE TITLE
System status page has tab overlapping title

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#524]
![screen shot 2016-12-07 at 4 00 17 pm](https://cloud.githubusercontent.com/assets/92044/20992025/58e68d52-bc96-11e6-8f46-9eead3c5397c.png)

**Comment by mjgiarlo** [comment]
:fire:

**Comment by laritakr** [comment]
Can anyone reproduce this? I'm not seeing any problem in either Chrome or Safari browsers.

**Comment by mjgiarlo** [comment]
Nope, you're right, @laritakr. This was fixed by another PR that failed to auto-close this issue. Closing.

Thanks!
