### ISSUE TITLE
[HyBox/production] RuntimeError: Unable to execute command "soffice --invisible --headless --convert-to pdf --outdir /tmp /var/app/current/tmp/uploads/j9/60/20/60/j9602060k20161212-24380-1kvlwg5". Exit code: pid 18356 exit 77
Error message: [Java framework] Error in function createSettingsDocument (elements.cxx).
javaldx failed!
Warning: failed to read path from javaldx

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#526]
## Backtrace

    line 25 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in perform_now
    line 41 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in switch
    line 40 of [PROJECT_ROOT]/lib/active_job_tenant.rb: switch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/31994162)

**Comment by hannahfrost** [comment]
I uploaded a .DOCX file to my generic work and it resulted in this error. It lacks thumbnail representation in the UI (broken image icon shows instead). Also, when I download the file, it has been converted from its original file format to a renamed, extension-less text file. 

I would expect the app to retain its DOCX encoding and display some common icon for office docs.
