### ISSUE TITLE
Visibility label is not displaying properly on the Works Listing

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#529]
![screenshot 2016-12-12 09 56 28](https://cloud.githubusercontent.com/assets/1801076/21110306/8b629c62-c051-11e6-80b0-7e109b62a754.png)

**Comment by mjgiarlo** [comment]
Related (possibly identical) to https://github.com/projecthydra-labs/hyrax/issues/20

**Comment by jcoyne** [comment]
Duplicate of #522
