### ISSUE TITLE
[HyBox/production] ActionView::Template::Error: PG::UndefinedColumn: ERROR:  column "login" does not exist
LINE 1: ...@example.com')) AND "users"."guest" = $1 ORDER BY login LIMI...
                                                             ^
: SELECT  "users".* FROM "users" WHERE (email not in ('batchuser@example.com','audituser@example.com')) AND "users"."guest" = $1 ORDER BY login LIMIT $2 OFFSET $3

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#531]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/31998382)

**Comment by mjgiarlo** [comment]
As an admin, I can create an Admin Set but when I click to the Admin Set's edit link, I am redirected back to its show page with the following flash notice: `You do not have sufficient privileges to edit this document`
