### ISSUE TITLE
Duplicate chevron in facet toggle

### ISSUE THREAD

**Issue by danhorst** [projecthydra-labs/hyku#532]
![double-chevron](https://cloud.githubusercontent.com/assets/2133/21154494/8b908596-c13c-11e6-951e-3276e7a8b752.png)

**Comment by andjsmit** [comment]
This issue appears in Hyrax as well and will need a simple fixed in both.

**Comment by andjsmit** [comment]
PR submitted in Hyrax as well: https://github.com/projecthydra-labs/hyrax/pull/39

**Comment by andjsmit** [comment]
I'm re-opening this issue until a PR in the works for Hyku is in place that removes duplicate styles which still cause the duplicate chevrons and a class name added that will prevent chevrons from disappearing in the admin sidebar.   ( #538 )
