### ISSUE TITLE
Inconsistent rendering of visibility options

### ISSUE THREAD

**Issue by danhorst** [projecthydra-labs/hyku#533]
On the edit form for a work, the institution-specific access option is displayed as text. All of the other permission options use the "pill" style label. Something like this wold work:

```
<span class="label label-info">Hydra-in-a-box</span>
```
(Except use the I8n key for the institution name)

![permission-badges](https://cloud.githubusercontent.com/assets/2133/21157562/cd9ea6ba-c147-11e6-8c36-58128759a5ec.png)

**Comment by jeremyf** [comment]
I believe we can change to include a span - https://github.com/projecthydra-labs/hyrax/blob/02be9977e93b6459cef9f009b7528fd427074d6b/config/locales/hyrax.en.yml#L531

**Comment by danhorst** [comment]
Fixed via projecthydra-labs/hyrax#31
Included via #534
