### ISSUE TITLE
can't add my work to my admin set

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#536]
I have two admin sets. I created a new work. On the new work's Relationships tab, I click on "Add as a member of administrative set", but the drop down list is empty.

I would expect to see my two admin sets listed there.

![screenshot 2016-12-14 11 10 02](https://cloud.githubusercontent.com/assets/1801076/21196825/f971b0ec-c1ed-11e6-98f7-bdc0565bca3a.png)

**Comment by jcoyne** [comment]
I suspect this is because you are not set up as a depositor on any administrative sets.

**Comment by hannahfrost** [comment]
Created #549. Closing this ticket
