### ISSUE TITLE
permissions issue when trying to transfer work

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#537]
When I am on my works dashboard and I select the "transfer ownership of work" action for a work, I get kicked over to the repository home page with a message "you are not authorized to access this page"

I would expect to be able to access the page where I can transfer my work

![screenshot 2016-12-14 16 04 02](https://cloud.githubusercontent.com/assets/1801076/21206550/aa4199fe-c217-11e6-9af7-fcc4853440ee.png)

**Comment by jcoyne** [comment]
I can't duplicate this:

<img width="1003" alt="screen shot 2016-12-16 at 4 13 02 pm" src="https://cloud.githubusercontent.com/assets/92044/21280287/a079b85e-c3aa-11e6-9391-d11f9c6de63f.png">

Is it still a problem for you?

**Comment by hannahfrost** [comment]
Yes, this is still a problem for me, @jcoyne

**Comment by jcoyne** [comment]
@hannah can you give me a step by step guide to recreate? Please start by making a new work.

**Comment by hannahfrost** [comment]
@jcoyne I tried but couldn't create a new work (got an error on saving a new generic work).

**Comment by jcoyne** [comment]
That new error is logged in #552, but I've yet to figure out to duplicate that.

**Comment by hannahfrost** [comment]
@jcoyne The step-by-step

- Create a new work (in this case: https://month12.demo.hydrainabox.org/concern/images/6108vb24b?locale=en#?c=0&m=0&s=0&cv=0)
- Go to My Works
- From the "Select an Action" menu, I click "Transfer ownership"
- Immediately kicked to the home page as described above

Does it matter if the work is shared with anyone before transfer? I would expect not, but I did test sharing with another user before transfer and the same thing happened.

(BTW I am not sure the sharing with others is working. The Share tab on Edit Work does not display the other user with whom I shared. Also no notifications of the action - which may or may not be expected behavior.)

Am I missing something?

**Comment by jcoyne** [comment]
@hannahfrost do you mean to say that when you click "Transfer ownership" you do not get to this screen?  
<img width="768" alt="screen shot 2016-12-19 at 10 25 22 am" src="https://cloud.githubusercontent.com/assets/92044/21320119/8a2ba83c-c5d5-11e6-8829-d3cff8a03227.png">

**Comment by hannahfrost** [comment]
@jcoyne Yes, that is what I am saying. I have never seen that screen in my entire life (no joke)

**Comment by hannahfrost** [comment]
@jcoyne I figured it out: the transfer feature was not enabled. It works as expected when enabled ;)

So, it sounds like we could use a ticket for removing this option from the "Select an Action" menu on the work page when the feature is not enabled.

**Comment by jcoyne** [comment]
Okay, I've opened #559
