### ISSUE TITLE
[HyBox/production] ActionView::Template::Error: undefined method `hyrax_generic_work_path' for #<#<Class:0x00556c916a0308>:0x00556c91698770>

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#548]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32041599)

**Comment by mjgiarlo** [comment]
@jcoyne this still on your plate?

**Comment by jcoyne** [comment]
Closed by https://github.com/projecthydra-labs/hyrax/pull/53
