### ISSUE TITLE
Featured researcher displays twice

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#555]
When "Explore collections" is deactivated, by turning the "Assign admin set" feature off. Then the heading "Featured researcher" displays twice.

<img width="1137" alt="screen shot 2016-12-19 at 12 00 54 pm" src="https://cloud.githubusercontent.com/assets/92044/21323452/250d825a-c5e3-11e6-9b56-632d2efad23e.png">

**Comment by laritakr** [comment]
Resolved by PR 577
