### ISSUE TITLE
Load a demo instance tenant with "lots of content"

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyku#556]
We should populate a Hyku tenant with hundreds of objects (or more) with rich metadata so that DPLA can harvest Hyku via ResourceSync.

**Comment by jcoyne** [comment]
For now "lots" is 25,000 items.

**Comment by hannahfrost** [comment]
[select_band.txt](https://github.com/projecthydra-labs/hyku/files/700303/select_band.txt)

**Comment by atz** [comment]
What blocks this?

**Comment by jcoyne** [comment]
@atz the improvements to the infrastructure that @bbranan and @eefahy were working on. They haven't yet been deployed on the demo site.

**Comment by atz** [comment]
2 months later, what blocks this?

**Comment by jcoyne** [comment]
@atz just @eefahy's other projects.

**Comment by mjgiarlo** [comment]
@eefahy when you back in pocket, I'd be interested to hear your assessment of where we stand w/ this stuff. Also pulling in @bbranan @dbernstein.

**Comment by mjgiarlo** [comment]
Blocked by https://github.com/projecthydra-labs/hyku/issues/724 ?

**Comment by hannahfrost** [comment]
See also #978 which essentially extends the work described in this ticket under a rebuilt stack with all the latest and greatest.

**Comment by mjgiarlo** [comment]
We no longer have a need to load lots of content for DPLA testing of ResourceSync (or MAP). We may want to continue doing this for load testing/stack robustness purposes, though. Closing this issue for now. If you think this is in error, re-open, pls!
