### ISSUE TITLE
DPLA should test Hyku's ResourceSync implementation

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyku#557]
By harvesting a given tenant URI. Discover the sitemap(s), parse the sitemap(s), dereference URIs, conneg to a known format, analyze "readiness" of data.

Assign to @mdellabitta?

Blocked by #556.

**Comment by mdellabitta** [comment]
Related DPLA ticket: https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1125

(Not public at the moment. Sorry.)

**Comment by jcoyne** [comment]
@mdellabitta Digital Private Library of America?

**Comment by mjgiarlo** [comment]
Blocked by https://github.com/projecthydra-labs/hyku/issues/556

**Comment by mjgiarlo** [comment]
This is now done.
