### ISSUE TITLE
Content Blocks

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyku#574]
When I open the "Content Blocks" option under settings, before selecting any tab, it shows the content of all the tabs. 

![screen shot 2017-01-04 at 2 38 42 pm](https://cloud.githubusercontent.com/assets/17851674/21656338/ba0afde2-d28b-11e6-9b3f-3de5658f9d9c.png)

**Comment by mjgiarlo** [comment]
@laritakr This may be related to TurboLinks. I had thought https://github.com/projecthydra-labs/hyku/commit/dd29b8b58dda3871ca051cfbe0eefd0c1ff0c30e would have fixed it. Alas, it didn't.

Perhaps the link in the menu ought to be to `#about_page`, or else we need some other way of making sure the page, when loaded, only renders the leftmost tab.

Thoughts on this, @jcoyne?

**Comment by mjgiarlo** [comment]
Should be fixed in Hyrax, methinks.
