### ISSUE TITLE
[HyBox/production] ActionView::Template::Error: No route matches {:action=>"show", :controller=>"hyrax/users", :id=>nil, :locale=>:en} missing required keys: [:id]

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#576]
## Backtrace

    line 27 of [PROJECT_ROOT]/app/views/hyrax/admin/_sidebar.html.erb: _app_views_hyrax_admin__sidebar_html_erb__3881427865678468897_70185302977060

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32218474)

**Comment by jcoyne** [comment]
This occurs when an unauthorized user goes to `/admin/workflows`. It looks like the unauthorized page is using the admin layout and attempts to draw the sidebar.
