### ISSUE TITLE
Missing radio label

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#585]
On the edit admin set page (https://nacho.demo.hydrainabox.org/admin/admin_sets/admin_set%2Fdefault/edit?locale=en#workflow):

<img width="976" alt="screen shot 2017-01-05 at 7 31 52 pm" src="https://cloud.githubusercontent.com/assets/92044/21704275/c1c4bae4-d37d-11e6-84c1-8bbf86e861f9.png">

It looks like this may be a relic from the old per-worktype workflows: 
<img width="597" alt="screen shot 2017-01-05 at 7 33 36 pm" src="https://cloud.githubusercontent.com/assets/92044/21704312/f7486936-d37d-11e6-999f-ac97d6021b74.png">

**Comment by mjgiarlo** [comment]
Ah. We may want to remove that old workflow, and we may also want to reimport the MD workflow which looks like it hasn't yet picked up the new JSON (which has a longer description than I'm seeing here).
