### ISSUE TITLE
"Create a new repository" form not working

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyku#601]
When I submit the https://demo.hydrainabox.org/account/sign_up?locale=en form, I am taken back to the same form with the fields reset. If I submit the form again with the same entries for title and short name, I am notified that the name I specified already exists. That implies to me that the first form submission was processed (at least partially), but instead of routing me to the account creation process... it did this.

**Comment by jcoyne** [comment]
I think this is due to #600. Solr timed out

**Comment by hannahfrost** [comment]
This is becoming a blocker for me.
