### ISSUE TITLE
Remove login from demo.hydrainabox.org

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#613]
When I go to demo.hydrainabox.org, I should not be able to login. I should only be able to click "Get Started" in order to create a repo. Login and the entire top banner of menus is only necessary in the tenant repository context

**Comment by cbeer** [comment]
In the future, we'll design a new and separate experience for things like account management by application owners?

**Comment by jcoyne** [comment]
@cbeer it sounds like you have some concerns about this.  Can you say more? Is there some functionality you are worried this removes?

**Comment by cbeer** [comment]
Most of the actions here, for one: https://github.com/projecthydra-labs/hyku/blob/master/app/controllers/accounts_controller.rb

**Comment by jcoyne** [comment]
@hannahfrost Given this information, would you care to revise this ticket?

**Comment by hannahfrost** [comment]
We're discussing this matter now through https://github.com/projecthydra-labs/hyku/issues/728 so I'm going to close this as a redundant ticket.
