### ISSUE TITLE
[HyBox/production] RuntimeError: Solr Extract service was unsuccessful. 'http://solr.demo.vpc.hydrainabox.org/solr//update/extract?extractOnly=true&wt=json&extractFormat=text' returned code 404 for /var/app/current/tmp/uploads/x6/33/f1/01/x633f101s/x633f101s20170117-24601-cd52f8
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr//update/extract. Reason:
<pre>    Not Found</pr...

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#618]
## Backtrace

    line 25 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in perform_now
    line 41 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in switch
    line 40 of [PROJECT_ROOT]/lib/active_job_tenant.rb: switch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32346743)

**Comment by jcoyne** [comment]
It appears that solr is not configured for text extraction.
