### ISSUE TITLE
repository not created

### ISSUE THREAD

**Issue by zschoenb** [projecthydra-labs/hyku#654]
Running in docker, after 'saving' a new repository, I am not forwarded to the correct path for the new repository. The forwarded location for a newly created repository named "repo" is http://repo.dev:8080/users/sign_up?locale=en

**Comment by zschoenb** [comment]
solved by adding repo.dev to my hosts file (0.0.0.0 repo.dev)

**Comment by mjgiarlo** [comment]
Good find, @zschoenb. Do you think this should be added to our README or a wiki page? If so, might you be inclined to contribute it?
