### ISSUE TITLE
app/views/accounts/_edit_form.html.erb is unneeded or untested

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyku#655]
This seems to have been replaced by `edit.html.erb`, corresponding to lines 8-58.  At best the partial is untested (I delete it and all tests pass).  But I also can't find anywhere it is invoked, referenced or rendered.  Could be cruft.  Can anyone vouch for its usefulness or should we just get rid of it?

**Comment by mjgiarlo** [comment]
:arrow_up: @cbeer :question:

**Comment by cbeer** [comment]
Looks like it was dropped in https://github.com/projecthydra-labs/hyku/commit/89d8135520d94eea74d5303dd2acfa82e2147c74?

**Comment by atz** [comment]
well, it was back for me to delete again in #f602e58c65ef0d52f36cf20e9ecce11e342e5f83
