### ISSUE TITLE
Default radio button should be selected on Admin Set > Workflow page

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#666]
Unless my local dev environment is not updated correctly, I think we need to update the Admin Set > Workflow page so that the first radio button, for "Default workflow," is checked. (Or, although I'm sure if we support this yet, whichever other workflow is the default workflow for new admin sets for the application.)

In other words, there should always be one currently selected item in this group of radio buttons, even for a new admin set.

![edit_admin_set____sample_digital_repository](https://cloud.githubusercontent.com/assets/101482/22270248/f1852c96-e24b-11e6-99f4-81d13b815cb3.png)

**Comment by hannahfrost** [comment]
:+1:

**Comment by jcoyne** [comment]
Tested and it is working now.
