### ISSUE TITLE
[HyBox/production] NameError: uninitialized constant ActiveFedora::SolrService
Did you mean?  ActiveFedora::SolrService

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#667]
## Backtrace

    line 19 of [PROJECT_ROOT]/app/models/solr_endpoint.rb: switch!
    line 51 of [PROJECT_ROOT]/app/models/account.rb: switch!
    line 51 of [PROJECT_ROOT]/config/initializers/apartment.rb: block (2 levels) in <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32435946)

**Comment by atz** [comment]
WAT?  Sure looks like it is suggesting the exact same thing it says doesn't exist.
