### ISSUE TITLE
[HyBox/production] NameError: uninitialized constant ActiveFedora::Fedora
Did you mean?  ActiveFedora::Fedora

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#677]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32442793)

**Comment by jeremyf** [comment]
Possibly closed by https://github.com/projecthydra/active_fedora/pull/1191
