### ISSUE TITLE
Change Workflow Review to Review Submissions

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyku#681]
Under the Tasks menu in the Admin Dashboard, change the label of the Workflow Review menu item to 'Review Submissions'. Use the icon specified in the mock-up. Also:

- [ ] change the page title to use the same label
- [ ] move Review Submissions to be the first task under the Tasks category (not shown in mock-up)

See mock-up:

![menu-item](https://cloud.githubusercontent.com/assets/101482/22302258/3655410e-e2eb-11e6-80c6-d0dc1c0c38c0.png)

This value is stored in Hyrax i18n at `'hyrax.admin.sidebar.workflow_review'` with both English and Spanish translations. Since the Hyku and Hyrax sidebars are somewhat divergent already and it doesn't seem timely to pay down that technical debt at this time, consider merely overriding the locales and views in Hyku.

Decomposed from design ticket #635.

**Comment by ggeisler** [comment]
I forgot to put this in #635 but I also suggest that the Review Submissions menu item be moved up so it is listed first under Tasks (given this is likely to be a very common task), not at the end as the mockup shows.

**Comment by mjgiarlo** [comment]
@ggeisler Got it.
