### ISSUE TITLE
Remove buttons from Profile page

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#687]
There are two Edit Profile buttons on a user's Profile page. "Edit Your Profile" appears in the upper right, and "Edit Profile" appears in the lefthand panel.  Let's lose one of them, probably the one on the right.

A "View Users" button appears on the user profile of an admin. This button should be removed, as the Users page is appropriately accessible from the dashboard.

**Comment by jcoyne** [comment]
I've done the first item, but the "View Users" button is not just for admins, it's for all users. It's so you can browse the depositors in the system.  See https://scholarsphere.psu.edu/users/nea11 for example.  Not all users will have access to the admin page.  Are you sure we want to remove that?

**Comment by hannahfrost** [comment]
@jcoyne Thanks. I didn't realize that. No, let's keep it.
