### ISSUE TITLE
HTML showing in file processing flash message

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyku#694]
After saving a new work:

![test_work_3](https://cloud.githubusercontent.com/assets/101482/22340525/f8254580-e3aa-11e6-9d21-77e18548a6fe.png)

**Comment by mjgiarlo** [comment]
I'm still seeing this. See discussion here:

https://github.com/projecthydra-labs/hyrax/pull/315#issuecomment-275548426

**Comment by mjgiarlo** [comment]
Update to @ggeisler -- the full fix now waiting here: https://github.com/projecthydra-labs/hyrax/issues/332
