### ISSUE TITLE
[HyBox/production] ActiveFedora::ObjectNotFoundError: ActiveFedora::ObjectNotFoundError

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#695]
## Backtrace

    line 25 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in perform_now
    line 41 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in switch
    line 40 of [PROJECT_ROOT]/lib/active_job_tenant.rb: switch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32459322)

**Comment by jcoyne** [comment]
Closing, because there's not enough here to be useful. The new version of AF provides more detail.
