### ISSUE TITLE
Document tenancy architecture

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyku#705]
You know, beyond the one sentence saying "we use apartment with postgres".  

The audience is developers and maintainers.  

Document should answer questions like:
- when does tenant switching get invoked? what is impacted?
- where in the DB does a given user account get stored?
- when do new users automatically get special roles/permissions?
- how do I test tenant-segregation in the interface? in spec?
- how does tenancy relate to DNS/hostname? how do I test that?
- how do I "see" a given tenant environment in `rails console`?

Diagram or flow chart might help also.

**Comment by atz** [comment]
Also, how do we run `db:migrate` against all tenant DB schemas?

**Comment by jcoyne** [comment]
This page? https://github.com/projecthydra-labs/hyku/wiki

**Comment by mjgiarlo** [comment]
@atz 
> how do I "see" a given tenant environment in rails console?
I believe that's the `AccountElevator.switch!` jazz in the README.

**Comment by atz** [comment]
@jcoyne: wiki location is fine, but you're not claiming all those points are covered in that doc.

**Comment by mjgiarlo** [comment]
Certainly not all those points. We need better documentation in this area.

**Comment by atz** [comment]
Related clarifications are needed around the expectations for our various levels of user permissions:
- Anonymous user
- Logged in user
- User with admin role
- User with superadmin role
- Edge case: User w/ superadmin but *not* admin role.  Is anything expected to be restricted?

Separately, we need to define what we expect to expose in the demo site, i.e. who is the audience?  Should everybody be able to create accounts and make themselves superadmins?  etc.

**Comment by atz** [comment]
See related DRAFT document to be finalized: https://docs.google.com/spreadsheets/d/1TSZ8CUuq6puwzyJ1Av0aQ798FOQZgzhkn2jaDYyt118/edit?pli=1#gid=0

**Comment by mjgiarlo** [comment]
@atz How close does the newly revised https://github.com/projecthydra-labs/hyku/wiki#multi-tenant-domain-model (HT to @tdonohue!) get us to closing this ticket?

**Comment by atz** [comment]
Yeah, closing this now.
