### ISSUE TITLE
[HyBox/production] Ldp::HttpError: STATUS: 403 <!DOCTYPE html><html><head><title>Apache Tomcat/8.0.36 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B...

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#709]
## Backtrace

    line 5 of [PROJECT_ROOT]/app/jobs/cleanup_account_job.rb: block in perform
    line 58 of [PROJECT_ROOT]/app/models/account.rb: switch
    line 3 of [PROJECT_ROOT]/app/jobs/cleanup_account_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32472223)

**Comment by jcoyne** [comment]
Same as #708
