### ISSUE TITLE
[HyBox/production] RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: 'Could not find collection : a56efe83-828e-41fc-adf7-422a10359269','rspCode'=>400},'error'=>{'metadata'=>['error-class','org.apache.solr.common.SolrException','root-error-class','org.apache.solr.common.SolrException'],'msg'=>'Could not find collection : a56efe83-828e-41fc-adf7-422a10359269','code'=>400}}

URI: http://solr.demo.vpc.hydrainabox.org/solr/admin/collections?wt=ruby&action=DELETE&name=a56efe83-828e-41fc-adf7-422...

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#710]
## Backtrace

    line 4 of [PROJECT_ROOT]/app/jobs/cleanup_account_job.rb: block in perform
    line 58 of [PROJECT_ROOT]/app/models/account.rb: switch
    line 3 of [PROJECT_ROOT]/app/jobs/cleanup_account_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32472304)

**Comment by jcoyne** [comment]
Caused by #711
