### ISSUE TITLE
Unable to search on the contents of DC:creator

### ISSUE THREAD

**Issue by danhorst** [projecthydra-labs/hyku#731]
### Expected behavior
Searching the name of a creator/depositor should return the records associated with that name.

### Actual behavior
Searching the name of a creator/depositor does not return any records, even if the name appears in the "Creator" facet.

### Steps to reproduce the behavior

1. Create a record with a value in the creator field
1. Search of the text of the creator field
1. Observe that there are no results

![hyku-731-results](https://cloud.githubusercontent.com/assets/2133/22608232/c1d927be-ea29-11e6-861c-ade3ec2001cf.png)
![hyku-731-search](https://cloud.githubusercontent.com/assets/2133/22608231/c1d8f4ec-ea29-11e6-8b04-7c3380168f7d.png)

Originally reported by @ruthtillman

**Comment by jcoyne** [comment]
This should be tokenize only on whitespace (not stemmed)
