### ISSUE TITLE
Create a rake task to add superadmin role to user account

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyku#733]
This allows us to be sure a deployed instance has at least one user with superadmin access. (At that point, the superadmin should use the new superadmin UI to create/remove tenants, create/remove tenant admins, and so forth. This is covered in another ticket.)

Note that spotlight has such a rake task.

**Comment by mjgiarlo** [comment]
Following from #728.

**Comment by hannahfrost** [comment]
Plase add hklein@duraspace.org to that list

**Comment by mjgiarlo** [comment]
Create a rake task to elevate an account's privileges to superadmin. Specify one or more email addresses. If account does not exist, print out a warning.

**Comment by cbeer** [comment]
I'm going to say 👎 . There's no reason we can't build a simple UI for this, especially since all the building blocks should be available.

**Comment by jcoyne** [comment]
@cbeer I think that's what we discussed the other day post standup.  We need a rake task to create the first superadmin and then a UI will be ideal for the rest.

**Comment by atz** [comment]
Is the rake task still the consensus direction?

**Comment by mjgiarlo** [comment]
AFAIK, yes, @atz.
