### ISSUE TITLE
[HyBox/production] MiniMagick::Invalid: image data can't be read

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#764]
## Backtrace

    line 26 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in perform_now
    line 42 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in switch
    line 41 of [PROJECT_ROOT]/lib/active_job_tenant.rb: switch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32636954)

**Comment by revgum** [comment]
If someone else stumbles upon this.. I had a background job failing with this error and ended up needing to `brew upgrade` Imagemagick and related libs. Also handy for debugging this was to configure Minimagick to use debug logging to see what commands the background job was running.
