### ISSUE TITLE
Visibility Level label on Save Work panel - "Hydra in a Box" is hard-coded in label for institution-only visibility

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#768]
I would expect to see the (short) name of my institution in the blue, institution-only visibility label on the Save Work panel, and in the brief line of text following the label. But it still shows "Hydra in a Box".  See screenshot.

The expected behavior is that the blue visibility label reflects the Repository Name  as entered on the Admin Dashboard, under Configuration > Settings > Labels
 
![screenshot 2017-02-12 14 55 29](https://cloud.githubusercontent.com/assets/1801076/22867016/1edb1b1e-f134-11e6-9674-19f773caa287.png)

**Comment by hannahfrost** [comment]
Noting that this same blue "Hydra in a Box" visibility label appears several other places, too: on the work page next to title; with each file listed under "Items"  on the same page,  and on the page that displays details of each file in a file set.

**Comment by atz** [comment]
I don't think it is hardcoded.  It appears to be set by the i18n file `config/locales/hyrax.en.yml` keys:
- **en.hyrax.institution_name**
- **en.hyrax.account_name**

See also, the Spanish counterpart, also.

**Comment by atz** [comment]
Your point about it not being specialized to the tenant repo name is correct, however.

**Comment by hannahfrost** [comment]
Moved and revised this issue at https://github.com/projecthydra-labs/hyrax/issues/404.

**Comment by hannahfrost** [comment]
Oops, didn't see your comments as I closed this, @atz . Would you mind adding them to hyrax#404?
