### ISSUE TITLE
making the Terms of Use configurable

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#769]
As the Repository Admin, I need to configure the text of the Terms of Use that is displayed to viewers from the repository home page. I need to apply basic formatting to the text and to be able to include active links. 

I would expect to be able configure the text in the Admin Dashboard, in the Content Blocks section under Settings.

**Comment by hannahfrost** [comment]
@mjgiarlo @jcoyne  This ticket and  https://github.com/projecthydra-labs/hyku/issues/770 need some discussion. I think it is safe to assume that customers of hosted Hyku will want to replace the language that ships with Hyrax for something more customized and will want an easy way to configure that. Given that there are variables used to pepper the language with the institution name and the repository name, is there one elegant way to handle this for both Hyku and Hyrax contexts? (I’m wondering if this is another distinction between the two: Hyku users want UI configurability; Hyrax implementors can do it via the back end.) I put these tickets here for now.

**Comment by mjgiarlo** [comment]
@jcoyne @hannahfrost I wonder if we shouldn't just use a content block here (in Hyrax). If folks insist on wanting to handle this OUTSIDE the UI... that seems like a follow-up enhancement.

**Comment by hannahfrost** [comment]
I'll recreate this ticket and #770 in Hyrax

**Comment by hannahfrost** [comment]
Moved this to its proper place in https://github.com/projecthydra-labs/hyrax/issues/406
