### ISSUE TITLE
README should document how to run tests

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/hyku#774]
Development without testing is irresponsible.  

Because of our **six**(!!) different processes running during development (and the conflicting expectations around port numbers for different RAILS_ENVs), knowing how to run the spec suite is not just counter-intuitive from a rails perspective, but uniquely complicated even as already cumbersome hydra processes go.  

Here's things that don't work, if you start from the end of the "For Development" steps:
- `bundle exec rake spec` - solr port errors
- `bundle exec rspec` - solr port errors
- `bundle exec rake ci` - modeshape errors
- `RAILS_ENV=test bundle exec rake spec` - solr port errors
- `RAILS_ENV=test bundle exec rspec` - solr port errors
- `RAILS_ENV=test bundle exec rake ci` - modeshape errors

Lots of `Failed to open TCP connection to 127.0.0.1:8986`, so solr apparently needing a different config (or in the case of :ci, maybe needing to be stopped/clean).  Basically, the docs are a setup for failure from the perspective of testing.

**Comment by jcoyne** [comment]
All of these work for me. `rake spec` and `rspec` require you to have solr & fedora running first.

**Comment by jcoyne** [comment]
@atz you could probably just copy this text into the README if you want: https://github.com/projecthydra/sufia/wiki/Sufia-Development-Guide#run-the-test-suite

**Comment by atz** [comment]
@jcoyne Except there is no internal test app for hyku.

**Comment by jcoyne** [comment]
@atz that's right. Some editing required.

**Comment by atz** [comment]
I was going off that same document previously, but for whatever shortcoming, imprecision or error on my part, it hasn't helped.
