### ISSUE TITLE
set fog_provider

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#789]
The carrierwave readme indicates that this is required, yet we don't have it (https://github.com/projecthydra-labs/hyku/blob/master/config/initializers/carrierwave_config.rb#L4-L12)
```ruby
  config.fog_provider = 'fog/aws'                        # required
```

@cbeer do you know if there's any reason we don't have this?

**Comment by jcoyne** [comment]
Possibly related to #802

**Comment by cbeer** [comment]
No. I would guess this was an upstream change?
