### ISSUE TITLE
[HyBox/production] ThreadError: can't create Thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#791]
## Backtrace

    line 26 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in perform_now
    line 42 of [PROJECT_ROOT]/lib/active_job_tenant.rb: block in switch
    line 41 of [PROJECT_ROOT]/lib/active_job_tenant.rb: switch

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32700159)

**Comment by jcoyne** [comment]
@eefahy @bbranan Hitting nproc or ulimit?

**Comment by bbranan** [comment]
Discussion here https://github.com/bundler/bundler/issues/4367 suggests it's hitting the nproc limit, either because that limit is too low or because threads aren't getting closed. On the worker instance, `ulimit -u` returns 15734.

**Comment by jcoyne** [comment]
How many concurrent jobs are being attempted on each worker box?
