### ISSUE TITLE
"Remember Me" not working

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#799]
After I have checked the "Remember Me" box at the time of signing in, when I return to log in after logging out, I do not see my email or password prepopulated in the sign in form as expected.

I'm suspicious this is limited to Hyku so submitting it here instead of in the Hyrax repo.

**Comment by cbeer** [comment]
All the "Remember Me" checkbox does is adds a cookie that will persist beyond your current browser session. If you explicitly log out, that cookie is destroyed. It also has nothing to do with the state of the sign in form; in fact, if your session is "remembered", you won't even see that form for 2 (?) weeks.

**Comment by hannahfrost** [comment]
Thanks for the explanation. I wonder if we should rephrase the checkbox label, eg., "Keep me signed in"

**Comment by mjgiarlo** [comment]
@hannahfrost Yes, that sounds reasonable to me and should be a quick fix in Hyku!
