### ISSUE TITLE
[HyBox/production] ActionView::Template::Error: Current page was incalculable. Perhaps you called .per(0)?

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#851]
## Backtrace

    line 66 of [PROJECT_ROOT]/app/views/admin/groups/index.html.erb: _app_views_admin_groups_index_html_erb___3262940546407534989_70144670975120

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32875852)

**Comment by mjgiarlo** [comment]
Fixed in `master`
