### ISSUE TITLE
[HyBox/production] ActiveModel::UnknownAttributeError: unknown attribute 'workflow_id' for Hyrax::PermissionTemplate.

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#853]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/32876326)

**Comment by mjgiarlo** [comment]
This happens when you try to change an AdminSet's workflow value.

**Comment by laritakr** [comment]
This is probably based on my hyrax changes, and something being incompatible with something from hyku, so it makes sense for me to look into this, but I can't access the backtrace.

**Comment by laritakr** [comment]
Ok never mind, I was able to duplicate the issue in localhost so I'm working on it.
