### ISSUE TITLE
PDF thumbnails are broken

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#861]
Ref https://github.com/projecthydra-labs/hyku/issues/860

This could be because openoffice is not installed or that imagemagick isn't compiled with the correct delegates.

**Comment by eefahy** [comment]
Uploaded a jpeg, svg, and a PDF. The PDF and the JPEG made a thumb fine after a little bit. There was also a delay on the creation of the larger thumb for the item show page. The SVG, however, did not create a thumb as we do not have an ImageMagick delegate configured for it. @hannahfrost Is it ok that we will not support SVG image files?

**Comment by jcoyne** [comment]
Closing as can't reproduce.
