### ISSUE TITLE
enable GeoNames and use URIs for dc:location metadata field

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#878]
We should do this for Generic Works and Image Works

**Comment by atz** [comment]
The latter part I understand, but I don't have a clear idea what "enable GeoNames" means.  Do you mean a process that would RESOLVE a string to remote URI and fetch enhanced geo data from it, like we did with the exhibits pipeline?  Or something else?

**Comment by hannahfrost** [comment]
@atz Yes, what you describe is what I mean.

**Comment by mjgiarlo** [comment]
@jcoyne Is this close-able? What is the remaining work if any?
