### ISSUE TITLE
[HyBox/production] Blacklight::Exceptions::InvalidSolrID: The solr permissions search handler didn't return anything for id "nope"

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#890]
## Backtrace

    line 8 of [PROJECT_ROOT]/app/services/iiif_authorization_service.rb: can?

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/33099903)

**Comment by jcoyne** [comment]
Fixed by #934
