### ISSUE TITLE
Workflows menu collapses when I choose "Review Submissions"

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#895]
It should stay expanded.

**Comment by hannahfrost** [comment]
The Settings menu also collapses when I choose any of the submenu items. It should also stay expanded.

**Comment by atz** [comment]
"Review submissions" is now top-level, so expanding is not an issue for it.  Settings menu is still a problem.

**Comment by atz** [comment]
Same with "Repository Activity" > "Activity Summary"

**Comment by atz** [comment]
Looks like Settings does:
```ruby
      <%= menu.collapsable_section t('hyrax.admin.sidebar.settings'),
                                   icon_class: "fa fa-cog",
                                   id: 'collapseSettings',
                                   open: menu.user_activity_section? do %>
```
Which is to say it repeats `open: menu.user_activity_section?`, so I can fix that at least.
