### ISSUE TITLE
As an admin user, I need to be able to access reports on activity and contents of my repository, to export those reports, and to update past reports

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#9]

**Comment by mjgiarlo** [comment]
Consider the following as a widget for the admin/reporting dashboard: https://github.com/projecthydra-labs/hybox-ideas/issues/29

**Comment by mjgiarlo** [comment]
As a start, take Sufia's built-in admin stats view, style it with Bootstrap basics, and add the following data:

* Number of collections
  * By creation date
* Number of works
  * By creation date
  * By resource type
* Downloads
  * Total overall
  * By file/work
  * By date
