### ISSUE TITLE
re-order and clean up the left sidebar menu

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#900]
Arrange the left sidebar menu like so:

> Activity
>> Repository activity
>> Your activity

>Repository Objects
>> Administrative Sets
>> Collections
>> Works

>Tasks
>> Review Submissions
>> Reports

> Configuration
>> Users and groups
>> Settings

**Comment by atz** [comment]
Deferring on this until several of the other sidebar PRs are merged, so as not to conflict.
