### ISSUE TITLE
Search dropdown menu says "Hyrax"

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#904]
It should be configured to display the Application Name as configured by the Repository Admin under Configuration > Settings > Labels. 

Eg., My application is called "Sandwich Repo" so the menu shows "All of Sandwich Repo"

**Comment by hannahfrost** [comment]
![screenshot 2017-04-04 10 53 13](https://cloud.githubusercontent.com/assets/1801076/24671202/95408eec-1925-11e7-8c19-ca00aa556487.png)

**Comment by atz** [comment]
Problem can be solved at Hyrax layer by having locales files reference `%{application_name}` instead of hardcoding "Hyrax".

**Comment by atz** [comment]
Fixed in https://github.com/projecthydra-labs/hyrax/pull/709
