### ISSUE TITLE
Broken image icon with label "Nope" is displayed while representative media is being processed

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#905]
### Descriptive summary

Generic file icon should be displayed while files are being processed immediately after deposit instead of a broken image icon with the accompanying label "Nope". 

### Expected behavior

As a depositor who has just submitted a work, I do not want to see a broken image icon with the label "nope" because it suggests that my deposit was not successful. 

![screenshot 2017-04-04 11 12 22](https://cloud.githubusercontent.com/assets/1801076/24672066/69a7077c-1928-11e7-8223-404310c43a9e.png)

### Actual behavior

As a depositor who has just submitted a work, I see a broken image icon with the label "nope" which sends me a negative message even though my files are most likely being processed successfully. 

![screenshot 2017-04-04 11 18 58](https://cloud.githubusercontent.com/assets/1801076/24672104/899766d0-1928-11e7-9c88-5d2265f66fdc.png)

**Comment by atz** [comment]
Weird, I suspect that is from `app/views/hyrax/base/_representative_media.html.erb`:
```ruby
<% if presenter.representative_id.present? %>
...
<% else %>
  <%= image_tag 'nope.png', class: "canonical-image" %>
<% end %>
```
`nope.png` was part of CurationConcerns (`app/assets/images/nope.png`), but it looks like it isn't in Hyrax anymore.  So even the placeholder for an unavailable image is broken.

**Comment by mjgiarlo** [comment]
@jcoyne didn't you fix this today?

**Comment by jcoyne** [comment]
Yes
