### ISSUE TITLE
depositor's dashboard should not display Configuration menu

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hyku#906]
A regular depositor with no permissions to configure the repository should not see the Configuration section on lefthand menu.

**Comment by ggeisler** [comment]
A depositor without admin permissions should probably also not see the "Repository activity" menu choice. They should only see the "Your activity" choice. (I believe non-admins currently see "Repository activity".)

**Comment by hannahfrost** [comment]
That's right too, @ggeisler ! Thanks.

**Comment by jcoyne** [comment]
Currently it is displaying:
<img width="223" alt="screen shot 2017-04-04 at 8 21 04 pm" src="https://cloud.githubusercontent.com/assets/92044/24685653/85da64e2-1974-11e7-8dcf-bd6551909b9d.png">

**Comment by jcoyne** [comment]
Fixed by #931
