### ISSUE TITLE
"Review submissions" is on the sidebar twice

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#910]
@ggeisler @hannahfrost where does it belong? Nested under "Workflows" or by itself?

<img width="221" alt="screen shot 2017-04-04 at 7 42 32 pm" src="https://cloud.githubusercontent.com/assets/92044/24684881/1811f5c4-196f-11e7-959a-0d357a8d9e12.png">

**Comment by ggeisler** [comment]
My opinion is it should just be "Review Submissions" without the Workflows heading.

The Roles page seems more like configuration to me and perhaps should be a menu item called "Workflow Roles" under Configuration, though I don't think I'm completely up-to-speed on how workflow roles fit into things.

**Comment by jcoyne** [comment]
Workflow Roles might be turned off for hyku. See https://github.com/projecthydra-labs/hyrax/issues/681
