### ISSUE TITLE
Hyku should support all of Hyrax's issue labels

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyku#936]
<a href="https://github.com/mjgiarlo"><img src="https://avatars3.githubusercontent.com/u/131982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mjgiarlo](https://github.com/mjgiarlo)**
_Monday Apr 10, 2017 at 21:17 GMT_
_Originally opened as https://github.com/projecthydra-labs/hyrax/issues/760_

----

This is a dummy issue that will convince the `github-issues-import` tool to create all of Hyrax's issue labels in Hyku.

**Comment by atz** [comment]
@mjgiarlo closable?

**Comment by mjgiarlo** [comment]
Yup! Thanks.
