### ISSUE TITLE
[HyBox/production] Riiif::ConversionError: Unable to execute command "convert -resize 300 -quality 85 -sampling-factor 4:2:0 -strip app/assets/images/us_404.svg jpg:-"
convert: not authorized `/tmp/magick-vP7Dkecg' @ error/constitute.c/ReadImage/454.
convert: no images defined `jpg:-' @ error/convert.c/ConvertImageCommand/3046.

### ISSUE THREAD

**Issue by cbeer** [projecthydra-labs/hyku#943]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/48327/faults/33264764)

**Comment by jcoyne** [comment]
Is it possible we build imagemagick without linking in librsvg?

**Comment by mjgiarlo** [comment]
@cbeer @eefahy :point_up:

**Comment by cbeer** [comment]
We're just installing the `ImageMagick` package from upstream, not building it ourselves:

https://github.com/projecthydra-labs/hyku/blob/master/.ebextensions/packages.config#L4
