### ISSUE TITLE
Banner image can't be removed

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hyku#960]
on the appearance form the "file" upload field is marked as required, so trying to submit the form without that prevents form submission.  We should mark the "file" file as not required.

**Comment by atz** [comment]
That corresponds to 
```html
<input class="file required" required="required" aria-required="true" type="file" name="admin_appearance[banner_image]" id="admin_appearance_banner_image">
```

**Comment by atz** [comment]
And this is because of simple_form.  Their README says `By default all inputs are required.`

**Comment by atz** [comment]
I propose to make the "remove" boolean into a submit button on its own form.  That is more distinct and appropriate, since those two fields *never* comingle beneficially.  Then the file would remain required for the form where it is actually required. Thoughts?

**Comment by ggeisler** [comment]
@atz Are you proposing something like this (just in terms of UI appearance)?

![show_appearance____hyku](https://cloud.githubusercontent.com/assets/101482/25345897/00c53ffa-28cb-11e7-8807-3ee29bfeacae.png)

If so, that seems good to me. I'd add a confirmation ("Are you sure you want to delete the banner image?") too.

Separately, I'm a bit concerned about the interaction here, given it's a required field. If we allow the user to remove the banner, that seems to imply it isn't required, unless we're somehow preventing the user from actually removing the banner image unless they replace it with a new one (which seems awkward).

Not sure if I'm misunderstanding something but I wonder if this really needs to be a required field? Though I think changing the checkbox to a button makes sense regardless.

**Comment by atz** [comment]
@ggeisler Right, though the remove button would only appear when there was an image to remove.  I can defer on the question of confirmation prompt: seems reasonable, but current flow doesn't include it.  

The file would remain required on the now distinct form that only deals with supplying a file (not it's removal).  It would not even be part of the removal 1-button form.

**Comment by ggeisler** [comment]
@atz Okay, but when you say "the remove button would only appear when there was an image to remove it" it sounds like the plan is to hide the button when no image has been added. If possible, it would be better if we could instead just add the `disabled` class to the button when there is no image to remove. That way the button is always there and the user learns that if they do upload an image, there is a way to remove it.

**Comment by hannahfrost** [comment]
:+1: to suggestion by @ggeisler. It would be good to fix this bug soon. I find that the user usually needs to tweak the banner a few times to get it right, especially since we provide insufficient help text on the screen right now. The user is almost guaranteed to not get it right the first time, and then they are stuck.

**Comment by atz** [comment]
@ggeisler I'm not feeling the rationale for a disabled button button here at all.  There are all kinds of features that we don't bother with advertising to the user until they are possible/enabled/necessary.  I might understand if this was a workstation console dashboard where seeing the disabled button informs them about state and preserves continuity of an established design or layout.  But this appears on literally one page for a one-off functionality.  The state is already obvious by **not having an image**, indeed would have been obvious to the user on every page before they even got to this one.  

Even on a very heavily used page like GMail, Google doesn't bother showing "Delete" until you've received message(s) AND selected one or more.  Similarly, once this fix is implemented, it will not be an area requiring **any** user education or foreknowledge that "someday delete is possible".  It will just be assumed that it always worked that way, as the obvious course of affairs.  

@hannahfrost You agree w/ Gary's suggestion, but all your statements are in support of just fixing the root problem, not arguing for a disabled button.

**Comment by ggeisler** [comment]
@atz If you don't want to deal with the disabled button, fine, it's not a huge issue. What we need is for the user to be able to actually remove an image, so they can add another one. Secondarily, a checkbox is not an ideal form control to use for this action; a button would be more appropriate.

**Comment by atz** [comment]
It's not a matter of complexity or aversion to the work: I think it is the wrong approach.  That would apply regardless of who does the implementation.  But thankfully we agree on the improved functionality, so I can move on that.
